ARROW-16817: [C++][Python] Fix segfaults in the ORC writer when unsupported datatypes are given
apache/arrow pull request #13531
Opened 2022-07-06 21:13 UTC by iajoiner

2022-07-07 15:45 UTC, iajoiner commented
Ok looks like the bug no longer exists in Arrow 8.0.0 likely due to the fix to https://issues.apache.org/jira/browse/ARROW-16025. These additional tests in C++ & Python are still good to add though just in case future updates break them.

2022-07-07 15:46 UTC, iajoiner commented
All tests have passed except for two that have nothing to do with the PR. Please review.

2022-07-11 13:10 UTC, pitrou requested changes
Thanks for doing this. This is probably a welcome addition; see some comments below.

2022-07-11 13:10 UTC, pitrou commented on cpp/src/arrow/adapters/orc/adapter_test.cc
> +#endif
This doesn't seem necessary, is it?

2022-07-11 13:10 UTC, pitrou commented on cpp/src/arrow/adapters/orc/adapter_test.cc
> +  const std::shared_ptr<Table> table = GenerateRandomTable(table_schema, 5332, 5, 7, 0);
Why 5332 rows? I would expect the error to show up even with a small number of rows. There's no reason to generate a lot of data here.

2022-07-11 13:10 UTC, pitrou commented on cpp/src/arrow/adapters/orc/adapter_test.cc
> +TEST_F(TestORCWriterInvalidTypes, noWriteInvalidTypes) {
The test name is cryptic. How are the types invalid? Why "noWrite"?

2022-07-11 13:10 UTC, pitrou commented on cpp/src/arrow/adapters/orc/adapter_test.cc
> +  TestORCWriterInvalidTypes() {
Usually this would be a `SetUp()` method instead.

2022-07-11 13:10 UTC, pitrou commented on cpp/src/arrow/adapters/orc/adapter_test.cc
> +  TestORCWriterInvalidTypes() {
```suggestion
  void SetUp() override {
```

2022-07-11 13:10 UTC, pitrou commented on cpp/src/arrow/adapters/orc/adapter_test.cc
> +    auto write_options = adapters::orc::WriteOptions();
`auto` declares a local variable, so this won't set the member variable.

2022-07-11 13:10 UTC, pitrou commented on cpp/src/arrow/adapters/orc/adapter_test.cc
> +  adapters::orc::WriteOptions write_options;
```suggestion
  std::shared_ptr<Schema> table_schema_;
  adapters::orc::WriteOptions write_options_;
```

2022-07-11 13:10 UTC, pitrou commented on cpp/src/arrow/adapters/orc/adapter_test.cc
> +  ASSERT_RAISES(NotImplemented, writer->Write(*table));
Also, for clarity, this should also check the message error (or some significant part thereof). You can look for instances of `EXPECT_FINISHES_AND_RAISES_WITH_MESSAGE_THAT` for examples.

2022-07-11 13:10 UTC, pitrou commented on cpp/src/arrow/adapters/orc/util.cc
> -    case Type::type::SPARSE_UNION: {
Why are these being removed? Is this addressing the same issue?

2022-07-11 13:10 UTC, pitrou commented on python/pyarrow/tests/test_orc.py
> +def test_orc_writer_with_arrays_with_unsupported_types():
There's a test on the C++ side, I don't think it's worth checking it a second time here. These tests should probably focus on exercising the Python APIs, not reproduce the existing C++ tests.

2022-08-08 15:41 UTC, pitrou commented
@iajoiner Ping.

2022-08-08 15:47 UTC, iajoiner commented
@pitrou Sorry yes. I’m mostly on the Rust side now but I will finish this one in a week.

2022-08-08 15:53 UTC, pitrou commented
@iajoiner Looking forward to it! (and glad to hear the Arrow Rust community is ever growing :-))

2022-08-25 11:51 UTC, pitrou commented
@iajoiner Are you willing to finish this?

2022-10-18 20:35 UTC, wjones127 commented
@pitrou Are we still trying to get this into 10.0.0? Or can this be bumped to 11.0.0?

I can work on this regardless.

2022-10-18 20:36 UTC, pitrou commented
It can probably be bumped IMHO.

2022-11-14 23:14 UTC, wjones127 commented
Closing in favor of #14638

2022-11-14 23:14 UTC, closed without merging