ARROW-17610: [C++] Support additional source types in SourceNode
apache/arrow pull request #14207
Opened 2022-09-22 12:55 UTC by rtpsw

See https://issues.apache.org/jira/browse/ARROW-17610

2022-09-22 12:57 UTC, rtpsw commented
cc @westonpace, @pitrou

2022-09-23 20:12 UTC, westonpace requested changes
I still think there is value in the user being able to specify the I/O executor.  I just think we should default it to the default I/O executor.

2022-09-23 20:12 UTC, westonpace commented on cpp/src/arrow/compute/exec/plan_test.cc
> +void test_source_sink_error(
```suggestion
void TestSourceSinkError(
```

2022-09-23 20:12 UTC, westonpace commented on cpp/src/arrow/compute/exec/plan_test.cc
> +void test_source_sink(
```suggestion
void TestSourceSink(
```

2022-09-23 20:12 UTC, westonpace commented on cpp/src/arrow/compute/exec/plan_test.cc
> +
```suggestion
TEST(ExecPlanExecution, ArrayVectorSourceSink) {
  TestSourceSink<std::shared_ptr<ArrayVector>, ArrayVectorSourceNodeOptions>(
      "array_vector_source", ToArrayVectors);
}

TEST(ExecPlanExecution, ArrayVectorSourceSinkError) {
  TestSourceSinkError<std::shared_ptr<ArrayVector>, ArrayVectorSourceNodeOptions>(
      "array_vector_source", ToArrayVectors);
}

TEST(ExecPlanExecution, ExecBatchSourceSink) {
  TestSourceSink<std::shared_ptr<ExecBatch>, ExecBatchSourceNodeOptions>(
      "exec_batch_source", ToExecBatches);
}

TEST(ExecPlanExecution, ExecBatchSourceSinkError) {
  TestSourceSinkError<std::shared_ptr<ExecBatch>, ExecBatchSourceNodeOptions>(
      "exec_batch_source", ToExecBatches);
}

TEST(ExecPlanExecution, RecordBatchSourceSink) {
  TestSourceSink<std::shared_ptr<RecordBatch>, RecordBatchSourceNodeOptions>(
      "record_batch_source", ToRecordBatches);
}

TEST(ExecPlanExecution, RecordBatchSourceSinkError) {
  TestSourceSinkError<std::shared_ptr<RecordBatch>, RecordBatchSourceNodeOptions>(
      "record_batch_source", ToRecordBatches);
}

```

2022-09-23 20:12 UTC, westonpace commented on cpp/src/arrow/compute/exec/options.h
> +  // the schema of the record batches from the iterator
```suggestion
  /// the schema of the record batches from the iterator
```

2022-09-25 13:19 UTC, rtpsw commented on cpp/src/arrow/compute/exec/options.h
> +class ARROW_EXPORT SchemaSourceNodeOptions : public ExecNodeOptions {
I'm not sure whether it is normal to expose an internal API, such as `arrow::internal::Executor`, in a public API such as here. I'll include it in the next commit, but please confirm this is acceptable.

2022-09-25 14:24 UTC, rtpsw commented
@westonpace, any idea how to fix the [Windows linker error here](https://github.com/apache/arrow/actions/runs/3122413945/jobs/5064339466)? In the past I was able to fix this by adding `inline` but this time it didn't work.

2022-09-25 15:38 UTC, rtpsw commented
> @westonpace, any idea how to fix the [Windows linker error here](https://github.com/apache/arrow/actions/runs/3122413945/jobs/5064339466)? In the past I was able to fix this by adding `inline` but this time it didn't work.

I suspect this is due to adding `Executor`, which is not a public symbol, in a constructor parameter as you requested. If so and we insist on exposing the IO executor, I see a couple of options to consider:
1. Make `Executor` a public symbol. I'm not sure what issues that might lead to.
2. Make `Executor` derive from a new type which would be a public symbol, and use this type in the constructor. This would lead to a not-so-pretty dynamic cast internally.
3. Expose one or more different (public-symbol) parameters that are used to internally setup the IO executor. This restricts the kind of IO executors that the caller may set up.

2022-09-25 17:33 UTC, westonpace commented
`Executor` is exported and it is included in other places that are part of the public API (e.g. SourceNodeOptions, CSV reader).

I think the problem is that `SchemaSourceNodeOptions` is templated.  Can you try adding something like (note, the first two lines already exist in your PR)...

```
using ArrayVectorIteratorMaker = std::function<Iterator<std::shared_ptr<ArrayVector>>()>;
using ArrayVectorSourceNodeOptions = SchemaSourceNodeOptions<ArrayVectorIteratorMaker>;
template class ARROW_EXPORT ArrayVectorSourceNodeOptions; // Explicitly export the specialization
```

2022-09-26 11:16 UTC, rtpsw commented
It turns out template instantiations and attributes (in this case, visibility) do not work together nicely. When I try adding code like `template<> class ARROW_EXPORT ArrayVectorSourceNodeOptions`, I get compiler errors like:
```
/mnt/user1/tscontract/github/rtpsw/arrow/cpp/src/arrow/compute/exec/options.h:113:31: error: using typedef-name ‘using ArrayVectorSourceNodeOptions = class arrow::compute::SchemaSourceNodeOptions<std::function<arrow::Iterator<std::shared_ptr<std::vector<std::shared_ptr<arrow::Array> > > >()> >’ after ‘class’
  113 | template<> class ARROW_EXPORT ArrayVectorSourceNodeOptions;
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
and when I try adding code like `template<> class ARROW_EXPORT SchemaSourceNodeOptions<ArrayVectorIteratorMaker>`, I get compiler warnings like:
```
/mnt/user1/tscontract/github/rtpsw/arrow/cpp/src/arrow/compute/exec/options.h:113:31: warning: attributes ignored on template instantiation [-Wattributes]
  113 | template<> class ARROW_EXPORT SchemaSourceNodeOptions<ArrayVectorIteratorMaker>;
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
So, both tries do not work, at least with my compiler. There seems to be a [proposal documenting this limitation](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0537r0.html), but I'm not sure what its status is.

In the commit I just made, I opted instead to explicitly define and export non-template symbols.

2022-09-27 06:36 UTC, rtpsw commented
The CI failures look unrelated to the PR.

2022-10-13 14:20 UTC, rtpsw commented
@westonpace, to make sure we're on the same page, what remains for this PR to go through?

2022-10-15 13:25 UTC, westonpace approved these changes
This looks good now and should be very useful for helping people get data into Acero, thanks!  I'll wait until after we make the RC branch (I think this happens on Monday) before I merge.

2022-11-06 14:03 UTC, rtpsw commented
@westonpace, is it a good time to get back to this PR?

2022-11-21 18:21 UTC, westonpace commented
Yes, apologies. Since it's been a month lets give it one last CI pass.  I've rebased this (all tests pass locally) and will merge later today.

2022-11-21 19:50 UTC, merged