ARROW-15641: [C++][Python] UDF Aggregate Function Implementation
apache/arrow pull request #14527
Opened 2022-10-27 08:14 UTC by vibhatha

Initial Draft of Aggregate UDFs for Python

- [ ] Improve the existing logic with more tests
- [ ] Find out a missing aggregate function and try to apply it with the current API (check if the applied theory sustains)
- [ ] Improvement function docs and comments
- [ ] Self-review

2022-11-02 09:30 UTC, vibhatha commented
cc @westonpace appreciate an initial review on the draft PR.

2022-11-16 06:45 UTC, westonpace requested changes
The shape of this looks correct.  I believe you are on the right track.  I think I would like to see at least one example of using a custom UDF in an exec plan.  Also, similar to scalar UDFs, I think we will eventually want an example that uses something other than pyarrow (e.g. numpy) to do the computation (at least for the consume function)

2022-11-16 06:45 UTC, westonpace commented on python/pyarrow/tests/test_udf.py
> +            self._non_null = value
I'm not much of a python expert but getters and setters seem like overkill here.  Are they needed?

2022-11-16 06:45 UTC, westonpace commented on python/pyarrow/tests/test_udf.py
> +        return state
```suggestion
        return State(0)
```

2022-11-16 06:45 UTC, westonpace commented on python/pyarrow/tests/test_udf.py
> +        elif isinstance(x, pa.Scalar):
Can a unary aggregate ever be called with a scalar?

2022-11-16 06:45 UTC, westonpace commented on python/pyarrow/tests/test_udf.py
> +    func_name = "simple_count"
Maybe `valid_count` or `non_null_count`?

2022-11-16 06:45 UTC, westonpace commented on python/pyarrow/tests/test_udf.py
> +            self._null = value
Same comment on getters and setters

2022-11-16 06:45 UTC, westonpace commented on python/pyarrow/tests/test_udf.py
> +        return state
```suggestion
        return State(0, 0)
```

2022-11-16 06:45 UTC, westonpace commented on python/pyarrow/tests/test_udf.py
> +        non_null = non_null + ctx.state.non_null
```suggestion
        non_null = non_null + ctx.state.non_null
        null = null + ctx.state.null
```

2022-11-16 06:45 UTC, westonpace commented on python/pyarrow/tests/test_udf.py
> +        return pa.array([ctx.state.non_null, ctx.state.null])
An aggregate UDF must always return an array of length 1.  Do you perhaps want something like...

```
return pa.array([{"non_null": ctx.state.non_null, "null": ctx.state.null}])
```

2022-11-16 06:45 UTC, westonpace commented on cpp/examples/arrow/udf_example.cc
> +     "This can be changed through SimpleCountOptions."),
Well, this isn't true quite yet :)

2022-11-16 06:45 UTC, westonpace commented on python/pyarrow/src/arrow/python/udf.cc
> +      throw std::runtime_error(st.ToString());
Is throwing an error the right thing to do?

2022-11-16 06:45 UTC, westonpace commented on python/pyarrow/src/arrow/python/udf.cc
> +      PyObject* init_res = result.obj();
Probably need to do sanity checking (e.g. not null, etc.) on things returned from user callbacks.

2022-11-16 06:45 UTC, westonpace commented on python/pyarrow/_compute.pyx
> +    terms of computation is very much similar to scalar functions.
```suggestion
    A scalar aggregate function is a set of 4 functions which are
    called at different times during the calculation of the aggregate.
```

I think we are missing a basic description first.  Something like:

```
An aggregate function reduces a column of values into a single aggregate result.
```

2022-11-16 06:45 UTC, westonpace commented on python/pyarrow/_compute.pyx
> +def register_scalar_aggregate_function(init_func, consume_func, merge_func, finalize_func,
Why "scalar aggregate"?  Is there a non-scalar aggregate?

2022-11-16 06:45 UTC, westonpace commented on python/pyarrow/_compute.pyx
> +    init_func : callable
Is `callable` the right word for python?  In python docs it refers to this kind of thing as `function` I think: https://docs.python.org/3/library/functions.html#map

2022-11-16 06:45 UTC, westonpace commented on python/pyarrow/_compute.pyx
> +        This function is used to set the state for the aggregate operation
I'm not sure that "set the state" is correct.  Maybe "create the initial state"?

2022-11-16 06:45 UTC, westonpace commented on python/pyarrow/_compute.pyx
> +        arguments.
How do varargs work?  Do I define a `*args`?

2022-11-16 06:45 UTC, westonpace commented on python/pyarrow/_compute.pyx
> +        autonomously handled in the C++ backend. The updated state must
I'm not sure I understand the sentence that starts with "The state doesn't need to be set..."

2022-11-16 06:45 UTC, westonpace commented on python/pyarrow/_compute.pyx
> +    merge_func: callable
The concept of a "merge function" is not going to be obvious to most users.  It is very possible for an engine to be defined that does not have to worry about the concept of a merge.  I think we need to describe some background here for why a merge is needed in the first place.  Something like:

Aggregates may be calculated across many threads in parallel.  Each thread will call the init function once to generate a state for that thread.  Once all values have been consumed then the threads from each state will be merged together to get the final result state.  The merge function should take two states and combine them.

2022-11-16 06:45 UTC, westonpace commented on python/pyarrow/_compute.pyx
> +        type must be an array matching the `out_type`.
In your C++ example the return type is a scalar?

2022-11-16 06:45 UTC, westonpace commented on python/pyarrow/_compute.pyx
> +        Using the context argument the state can be extracted and return
"the state can be extracted" is not very obvious.  Maybe something like:

The purpose of the finalize function is to transform the state (which is available in the context argument) into an array.  This array will be the final result of the aggregation.

2024-02-05 13:21 UTC, closed without merging