Bugfix: [JS] Using tableFromIPC().toString() results in invalid stringified JSON when containing dates
apache/arrow pull request #14984
Opened 2022-12-15 19:45 UTC by arteconceito

This PR fixes the bug reported by #14973 leveraging the native JavaScript `JSON.stringify()` function to serialize an Arrow Table into a valid JSON string. The use of this native function guarantees that all data types will be serialised into valid ones. This allows the reverse operation of deserialising the same string back into a JavaScript object through the use of `JSON.parse()`.

2022-12-19 10:28 UTC, arteconceito commented
Hi @AlenkaF
This failing test above, is it worth re-running it? Or, do you know anyone who may know what it is about?
Thanks in advance.

2022-12-19 18:52 UTC, trxcllnt requested changes
I believe the Vector and Row have a `toJSON()` method. Could we implement this as a new `toJSON()` method on Table (and ideally RecordBatch)?

2022-12-19 19:22 UTC, arteconceito commented
Yeah, sure @trxcllnt. Whenever I have some time I will look into that 👍

2022-12-22 16:33 UTC, arteconceito commented
@trxcllnt I had a look at the `.toJSON()` methods and I do not see any issue there as those methods return JavaScript objects, not strings. The issue being solved here is only when JavaScript objects are serialised to strings over the `.toString()` methods. I will go over those `.toString()` methods and fix where necessary.

Let me know in case I am missing something. Thx!

2022-12-22 16:44 UTC, domoritz commented
I want to note that the goal of `toString` is not to produce a de-serializable representation. `toJSON` should produce valid JSON.

2022-12-22 16:55 UTC, arteconceito commented
What you describe @domoritz  is in fact consistent to what happens for example with `new Date().toJSON()`. In such case you get a JSON serialised date string. But, I want to point out that the current implementation of the `.toJSON()` methods does not follow that principle, rather behaves as I described [here](https://github.com/apache/arrow/pull/14984#issuecomment-1363062607).

2022-12-22 17:04 UTC, domoritz commented
Do I follow correctly that the proposed fix in this pull request is not the final patch you want us to review? If so, can you mark it as a draft and ping us when it's ready?

2022-12-22 20:16 UTC, arteconceito commented
As discussed [here](https://github.com/apache/arrow/pull/14984#issuecomment-1363062607), I am closing this PR as it is no longer relevant.

2022-12-22 20:16 UTC, closed without merging