ARROW-2102: [C++] Implement take kernel functions - primitive value type
apache/arrow pull request #1563
Opened 2018-02-06 22:27 UTC by alphalfalfa

Currently the take kernel supports:
- Primitive value types (NA, Boolean and numeric types)
- Single numeric index
- Multiple flat indices in an array

The kernel does not yet handle special indices including negative integers or out-of-bound indices. ARROW-2105 is created for such feature.

2018-02-06 22:28 UTC, alphalfalfa commented
@wesm @xuepanchen

2018-02-12 19:41 UTC, wesm commented
@alphalfalfa thank you for starting on these kernels; I'm sorry it's taken me a little while to get down to review but I intend to do so this week

2019-02-12 14:18 UTC, fsaintjacques requested changes

2019-02-12 14:18 UTC, fsaintjacques commented on cpp/src/arrow/compute/kernels/take.cc
> +      if (BitUtil::GetBit(input_data, *index_data++)) {
Ditto with null bitmap.

2019-02-12 14:18 UTC, fsaintjacques commented on cpp/src/arrow/compute/kernels/take.cc
> +    std::stringstream ss;
No need stringstream, see other comment on the subject.

2019-02-12 14:18 UTC, fsaintjacques commented on cpp/src/arrow/compute/kernels/take.cc
> +typedef std::function<void(FunctionContext*,
Why the typedef, can it just pass the Functor arround?

2019-02-12 14:18 UTC, fsaintjacques commented on cpp/src/arrow/compute/kernels/take.cc
> +class TakeKernel<Int32Type> : public UnaryKernel {
Why `Int32Type`, this seems fishy as it doesn't seem used in the rest of the code.

2019-02-12 14:18 UTC, fsaintjacques commented on cpp/src/arrow/compute/kernels/take.cc
> +  static std::unique_ptr<UnaryKernel> Get##ValueType##TakeFunc(                \
I'd make this function return Status and pass the unique_ptr by output parameter (as the parent callsite is also doing).

2019-02-12 14:18 UTC, fsaintjacques commented on cpp/src/arrow/compute/kernels/take.cc
> +      func(ctx, options, input, indices, out);                                          \
There's way too much `func` shadowing involved here.

2019-02-12 15:10 UTC, wesm commented
As this PR is over a year old I think it probably needs a fresh start

2019-03-13 01:28 UTC, wesm commented
Closing in favor of new PR, thank you for starting on this @alphalfalfa!

2019-03-13 01:28 UTC, closed without merging