ARROW-347: Add method to pass CallBack to get Transfer Pair
apache/arrow pull request #182
Opened 2016-10-20 23:38 UTC by StevenMPhillips

2016-10-24 16:52 UTC, julienledem requested changes
Hi @StevenMPhillips 
See my comments bellow

2016-10-24 16:52 UTC, julienledem commented on java/vector/src/main/codegen/templates/UnionVector.java
> +    return getTransferPair(ref, allocator, null);
why do we need to keep this method?

2016-10-24 16:52 UTC, julienledem commented on java/vector/src/main/java/org/apache/arrow/vector/BaseDataValueVector.java
> +    return getTransferPair(ref, allocator);
why do we drop the callback here?

2016-10-24 16:52 UTC, julienledem commented on java/vector/src/main/java/org/apache/arrow/vector/ValueVector.java
> +  TransferPair getTransferPair(String ref, BufferAllocator allocator, CallBack callBack);
why don't we just add a parameter to the existing method?
We should avoid duplicating those methods unless necessary.
Please add javadoc to interface/abstract methods

2016-10-24 16:52 UTC, julienledem commented on java/vector/src/main/java/org/apache/arrow/vector/complex/ListVector.java
> +    return null;
? that's different from the original behavior. What's the intent?

2016-10-24 16:52 UTC, julienledem commented on java/vector/src/main/java/org/apache/arrow/vector/complex/NullableMapVector.java
> +    return new NullableMapTransferPair(this, new NullableMapVector(ref, allocator, null), false);
could just call the other one with null param

2016-10-24 16:52 UTC, julienledem commented on java/vector/src/main/java/org/apache/arrow/vector/complex/NullableMapVector.java
> +    return new NullableMapTransferPair(this, new NullableMapVector(name, allocator, null), false);
could just call the one bellow with name as ref.

2016-12-02 16:52 UTC, wesm commented
@StevenMPhillips ping, also needs rebase

2016-12-13 17:05 UTC, wesm commented
ping, can we close out all the Java PRs in advance of Arrow 0.2?

2017-01-06 15:58 UTC, wesm commented
Pinging again on this

2017-01-12 00:03 UTC, julienledem commented
@StevenMPhillips can you rebase and respond to comments?

2017-03-16 19:58 UTC, wesm commented
pinging on this one

2017-03-23 03:09 UTC, closed without merging