ARROW-350: Added Kerberos to HDFS client
apache/arrow pull request #185
Opened 2016-10-27 22:10 UTC by chrisaycock

2016-10-28 01:24 UTC, wesm requested changes

2016-10-28 01:24 UTC, wesm commented on cpp/src/arrow/io/hdfs.h
> +  std::string kerb;
Can you give this a more descriptive name, like `kerberos_ticket_path`

2016-10-28 01:24 UTC, wesm commented on python/pyarrow/io.pyx
> +        kerb : Path to Kerberos ticket cache.
Same comment as above

2016-10-28 01:24 UTC, wesm commented on python/pyarrow/io.pyx
> +            conf.host = tobytes(host)
Is `None` a valid option?

2016-10-28 14:06 UTC, chrisaycock commented
A `None` host is valid from the standpoint of libhdfs. Here's the doc from `hdfs.h`:

> If NULL is given, a LocalFileSystem will be created.

I'm not sure why they chose to specify the default host with `"default"`, but I wanted to keep my parameter values consistent with the C++.

I'll rename the `kerb` parameter.

2016-10-29 01:11 UTC, wesm commented
+1

2016-10-29 01:13 UTC, closed without merging