ARROW-2368: [Java] Add list<decimal> writer
apache/arrow pull request #1965
Opened 2018-04-30 06:55 UTC by pudidic

Apache Arrow have writer interface for list of decimal without implementation. It will follow the current interface and will infer the scale from BigDecimal or DecimalHolder if it can.

cc @wesm

2018-05-01 09:58 UTC, xhochy requested changes
The unit tests fail with 

```
[ERROR] Failures: 
[ERROR]   TestComplexWriter.listDecimalType:285 expected:<1> but was:<972208782254614709842509301809153>
```

2018-05-10 05:51 UTC, pudidic commented
Fixed wrong test code. Thanks for feedback.

2018-05-10 09:35 UTC, xhochy approved these changes

2018-05-10 09:36 UTC, xhochy commented
cc @jacques-n @icexelloss @siddharthteotia @BryanCutler

2018-05-10 17:46 UTC, BryanCutler reviewed
Thanks for the PR @pudidic.  The linked JIRA is wrong though, I think it should be ARROW-2517.  I don't normally use the writer interface, so I only made a quick pass but I'm not too sure why you need to use the ArrowType when setting the writer.  I believe there is already an interface that allows you to set the scale and precision.  Could you elaborate on that a little?  Maybe @siddharthteotia can take a closer look.

2018-05-10 17:46 UTC, BryanCutler commented on java/vector/src/main/codegen/templates/AbstractPromotableFieldWriter.java
> +  abstract protected FieldWriter getWriter(MinorType type, ArrowType arrowType);
Could you elaborate on why you need to add the `arrowType`?

2018-05-11 23:03 UTC, siddharthteotia approved these changes
LGTM

2018-05-11 23:04 UTC, merged