ARROW-2278: [Python] Fix incorrect numpy struct array serialization
apache/arrow pull request #1995
Opened 2018-05-04 06:52 UTC by Licht-T

This fixes [ARROW-2278](https://issues.apache.org/jira/browse/ARROW-2278).

2018-05-07 10:49 UTC, pitrou requested changes
@Licht-T, thanks for posting this. Please address the review comments below.

2018-05-07 10:49 UTC, pitrou commented on python/pyarrow/serialization.py
> +            dtype = DTypeJsonEncoder().encode(dict(obj.dtype.fields))
I think it's overkill to bring json into this and customize the encoder. You could simply use pickle, which Numpy dtypes support natively (you could also use `dtype.descr`, but it won't work with all dtypes).

2018-05-07 10:49 UTC, pitrou commented on python/pyarrow/tests/test_serialization.py
> +import pandas.util.testing as tm
You don't need this, just use `numpy.testing.assert_array_equal`.

2018-05-07 13:25 UTC, Licht-T commented
Thanks @pitrou, fixed!

2018-05-07 14:51 UTC, pitrou commented
Yes, `npm` looks flaky these days unfortunately.

2018-05-07 14:56 UTC, pitrou commented on python/pyarrow/serialization.py
> +        except (TypeError, pickle.UnpicklingError):
I don't think we should try to unpickle data that we know isn't a pickle (in extreme cases there may even be false positives, though that's unlikely). Rather, perhaps we should change the serialization format for Numpy arrays. For example a 3-tuple `(kind, serialized dtype, data)`. The `kind` (for example a string: "object", "struct", "scalar") would help discriminate between different serialization formats. After all we already have a distinct deserialization path for object arrays.

2019-05-17 23:00 UTC, wesm commented
@Licht-T I know it's been a long time but would like to rebase and perhaps address @pitrou's feedback?

2019-05-22 19:00 UTC, wesm commented
Closing for now for staleness

2019-05-22 19:00 UTC, closed without merging