[Arrow-2486] [C++/Python] Provide a Docker image that contains all dependencies for development
apache/arrow pull request #2016
Opened 2018-05-09 07:59 UTC by akarve

Open items
- [ ] Why is `py.test pyarrow` failing on plasma deps when script follows [docs](https://arrow.apache.org/docs/python/development.html#developing-on-linux-and-macos)?
- [ ] Unit tests needed?
- [ ] Should `/script/*.sh` use the same code as developer docs to avoid denormalization? 
- [ ] Move docker image to Apache registry?
- [ ] Multiple container strategy possible, but overly complex. Requires exposing volume on one container as a mount point for a second container. Only really speeds up first build
- [ ] Update README per resolution of above

2018-05-09 12:42 UTC, xhochy requested changes
This looks good for a first round, thanks for taking a step at this.

To get the Plasma tests running you need to do `docker run --shm-size=2g …`

2018-05-09 12:42 UTC, xhochy commented on dev/dev_container/Dockerfile
> +RUN apt-get -y install gcc-4.8
No, we can use different versions of gcc, we need to highlight this better in the documentation. For newer GCC versions, be aware of https://arrow.apache.org/docs/python/development.html#known-issues

2018-05-09 12:42 UTC, xhochy commented on dev/dev_container/Dockerfile
> +RUN apt-get -y install vim
Please combine all `apt` steps into a single `RUN` call, see https://github.com/apache/arrow/pull/1787/files

2018-05-09 12:42 UTC, xhochy commented on dev/dev_container/Dockerfile
> +RUN conda create -y -q -n pyarrow-dev \
Run `conda clean --all` afterwards in the same `RUN` step so that the conda cache is not persisted in the image.

2018-05-09 12:42 UTC, xhochy commented on dev/dev_container/Dockerfile
> +RUN apt-get -y install make
Install `ninja-build` also and use that later for more efficient builds

2018-05-09 12:42 UTC, xhochy commented on dev/dev_container/script/arrow-build.sh
> +mkdir -p /vol/arrow/cpp/build
We should call `/vol` simply `/io`. We do use that folder name in the other docker files (e.g. the `manylinux1` ones).

2018-05-09 12:42 UTC, xhochy commented on dev/dev_container/script/arrow-build.sh
> +      -DARROW_BUILD_TESTS=OFF \
Add a `-GNinja` here and uns `ninja install` afterwards. `ninja` is a bit more efficient than `make`. We simply don't mention it in the docs as it is not always installed but in the case of the docker container, we can control that.

2018-05-09 12:42 UTC, xhochy commented on dev/dev_container/script/parquet-build.sh
> +      ..
Same thing with `ninja` here

2018-05-09 18:34 UTC, akarve commented
@xhochy Thanks for the feedback. I believe that it has all been addressed. The container uses GCC/G++ 8 and ninja (with the `CXXFLAGS` fix). All build scripts succeed and `py.test pyarrow` produces `778 passed, 55 skipped, 4 xfailed, 8 warnings`.

2018-05-14 13:47 UTC, akarve commented
@xhochy done - the rebase didn't help though, it seems `master` is failing as well on gcc / C++

2018-05-14 15:41 UTC, akarve commented
Actually, all good as of re-merging this AM's `master`

2018-05-15 17:14 UTC, xhochy requested changes
Small comment, then this is ready to be merged.

2018-05-15 17:17 UTC, xhochy commented
Opened an issue with INFRA about the Docker Hub usage: https://issues.apache.org/jira/browse/INFRA-16533

2018-05-15 19:15 UTC, akarve commented
Ugh, bad merge. Will fix this PR after I land. All dependencies build in the latest container. I note that `py.test pyarrow` started failing on a plasma issue somewhere between 63da09a89ec1f88881110a5d1030fc32fafad8ed
and 48eee79189ca287ed58f3ae7833eaea011cdf5f8; but I don't think that's related to this patch.

2018-05-16 17:45 UTC, akarve commented
OK, pending CI, I think we're good to go
* [ ] PR feedback addressed
* [ ] Commits squashed

Testing
* [ ] Arrow CPP builds
* [ ] Parquet builds
* [ ] PyArrow builds
* [ ] py.test pyarrow (`782 passed, 55 skipped, 4 xfailed, 8 warnings`)

2018-05-17 13:46 UTC, xhochy approved these changes
+1, LGTM.

I'll merge this and follow-up on the automated build of the base image once INFRA got back to me about docker hub.

2018-05-17 13:50 UTC, closed without merging

2018-05-21 23:32 UTC, wesm commented
Once we are able to perform arbitrary nightly builds, we'll definitely want to run this build to prevent bitrot

2018-05-22 00:39 UTC, akarve commented
Ideally the build recipes in `/script` become part of CI, so we know when they break.

The container needs to be rebuilt if and only if `Dockerfile` or `/script/*.sh` changes.

2018-05-22 00:50 UTC, wesm commented
Right, when I say "nightly builds" I think of it as "nightly CI". Running these scripts on each commit might be overkill (the CI matrix is already growing quite big).