Add more common problems compiling c_glib on OSX
apache/arrow pull request #2107
Opened 2018-06-05 12:59 UTC by stephenpascoe

A couple of extra problems I had compiling c_glib on OSX.  Possibly not "common" enough to warrant a merge but here for reference.

2018-06-06 00:46 UTC, kou requested changes
Good catch!

Can you create a ticket on JIRA: https://issues.apache.org/jira/browse/ARROW

Example:

  * https://issues.apache.org/jira/browse/ARROW-2064

And can you prepened the created JIRA ticket ID to your title with "ARROW-XXX: " format.

Example:

  * https://github.com/apache/arrow/pull/1537

JIRA tickets are used to generate changes in release note automatically: https://arrow.apache.org/release/0.9.0.html

2018-06-06 00:46 UTC, kou commented on c_glib/README.md
> +On OSX you may need to set the following environment variable:
Can you use "macOS" instead of "OSX"? We use the latest OS name in this document.

2018-06-06 00:46 UTC, kou commented on c_glib/README.md
> +% export XML_CATALOG_FILES="/usr/local/etc/xml/catalog" required to build docs
Is " required to build docs" garbage?

2018-06-06 00:46 UTC, kou commented on c_glib/README.md
> +On OSX if you see the following error you may need to upgrade `source-highlight`
Ditto.

2018-06-07 00:50 UTC, closed without merging

2018-06-07 00:53 UTC, kou commented
+1
I've merged. Thanks!

@xhochy @wesm Can you tell me how to set Stephen Pascoe as the Assignee to JIRA ticket? https://issues.apache.org/jira/browse/ARROW-2678
JIRA doesn't show him on Assignee field. (Or we don't need to set the Assignee field?)

2018-06-08 14:37 UTC, xhochy commented
@kou Assigned Stephen Pascoe and made you an administrator of the JIRA projects. You can now add users to the Contributors role in the project. Then they can self-assign tickets.

2018-06-11 04:36 UTC, kou commented
@xhochy Thanks!