ARROW-3124: [C++] Disable insecure warnings in MinGW build
apache/arrow pull request #2539
Opened 2018-09-11 01:16 UTC by kou

It's already disabled in MSVC build.

2018-09-11 01:18 UTC, kou commented
You can see the important changes easily by disabling whitespace changes by https://github.com/apache/arrow/pull/2539/files?w=1 .

2018-09-11 14:24 UTC, pitrou requested changes
LGTM, just one nit below.

2018-09-12 00:37 UTC, kou commented on cpp/cmake_modules/SetupCxxFlags.cmake
> +  endif()
That makes sense.
I've added.

2018-09-12 12:00 UTC, xhochy approved these changes
+1, LGTM

2018-09-12 12:01 UTC, closed without merging