ARROW-3231: [Python] Sphinx's autodoc_default_flags is now deprecated
apache/arrow pull request #2554
Opened 2018-09-13 13:40 UTC by kszucs

2018-09-13 13:55 UTC, kou approved these changes
+1
CI isn't finished yet but I think that this will fix the failure too.

2018-09-13 14:22 UTC, kou requested changes
CI is failed...

2018-09-13 14:46 UTC, kszucs commented on python/doc/source/conf.py
> +                           'inherited-members']
Thanks for the update and reference! Fixing it...

2018-09-14 18:54 UTC, wesm commented
+1

2018-09-14 18:54 UTC, closed without merging

2018-09-14 19:55 UTC, kszucs commented
Sphinx 1.8.0 raised a couple of other warning locally so pinning was quicker. Thanks for removing the unused import!