ARROW-108: [C++] WIP: Add Union implementation and IPC/JSON serialization tests
apache/arrow pull request #264
Opened 2017-01-02 16:16 UTC by wesm

Closes #206.

Still need to add test cases for JSON read/write and dense union IPC. Integration tests can happen in a subsequent PR (but the Java library does not support dense unions yet, so sparse only -- i.e. no offsets vector)

2017-01-02 17:45 UTC, xhochy requested changes
I see that you have changed  `ArrayPtr` in a lot but not all places. The changes adds more characters but in the end, it's more readable because it actually tells one that it is a `shared_ptr`. But then it would be better if we would get rid of it completely.

2017-01-02 17:45 UTC, xhochy commented on cpp/src/arrow/array.h
> +      std::vector<std::shared_ptr<Array>>& children,
const?

2017-01-02 17:45 UTC, xhochy commented on cpp/src/arrow/array.h
> +      std::shared_ptr<Buffer> null_bitmap = nullptr);
const ref

2017-01-02 19:53 UTC, wesm commented
Tests are completed

2017-01-02 19:54 UTC, wesm commented on cpp/src/arrow/array.h
> +      std::vector<std::shared_ptr<Array>>& children,
done

2017-01-02 19:54 UTC, wesm commented on cpp/src/arrow/array.h
> +      std::shared_ptr<Buffer> null_bitmap = nullptr);
done

2017-01-02 19:54 UTC, wesm commented
Removed ArrayPtr completely

2017-01-03 06:57 UTC, xhochy approved these changes
+1, LGTM

2017-01-03 07:28 UTC, closed without merging