Use virtual inheritance for diamond inheritance
apache/arrow pull request #282
Opened 2017-01-13 02:01 UTC by kou

arrow::io::ReadWriteFileInterface inheritances arrow::io::FileInterface
as diamond style via:

  * ReadableFileInterface -> InputStream -> FileInterface
  * WriteableFileInterface -> OutputStream -> FileInterface

If we have diamond inheritance, we can't cast subclasses of
arrow::io::ReadWriteFileInterface such as arrow::io::MemoryMappedFile to
arrow::io::FileInterface.

C++:

    #include <arrow/io/file.h>

    int
    main(void)
    {
      std::shared_ptr<arrow::io::MemoryMappedFile> memory_mapped_file;

      std::shared_ptr<arrow::io::FileInterface> file = memory_mapped_file;

      return 0;
    }

Build result:

    a.cc: In function 'int main()':
    a.cc:8:52: error: conversion from 'std::shared_ptr<arrow::io::MemoryMappedFile>' to non-scalar type 'std::shared_ptr<arrow::io::FileInterface>' requested
       std::shared_ptr<arrow::io::FileInterface> file = memory_mapped_file;
                                                        ^~~~~~~~~~~~~~~~~~

We can resolve it by using virtual inheritance.

2017-01-13 02:02 UTC, kou commented
I couldn't create an issue at JIRA because issues.apache.org is down now. Sorry.

2017-01-13 13:49 UTC, wesm commented
The JIRA appears to be back up. Can you also add a unit test (what you have in the PR description is sufficient)? thanks!

2017-01-13 14:55 UTC, kou commented
> Can you also add a unit test?

Sure. I've added. Could you confirm it?

2017-01-13 15:36 UTC, wesm approved these changes
+1, thank you for the contribution!

2017-01-13 15:37 UTC, wesm commented
Could you create a JIRA and prefix the PR title with "ARROW-XXX"?

2017-01-13 18:56 UTC, wesm requested changes
Let me know when you've fixed the unit test and I will merge

2017-01-15 06:51 UTC, kou commented
I've created an issue on JIRA and fixed the test.

2017-01-15 10:40 UTC, xhochy approved these changes
Can you prefix the PR with `ARROW-486: `?

2017-01-15 14:24 UTC, kou commented
Done.
Sorry. I changed title form content but forgot to submit the change.

2017-01-15 17:19 UTC, closed without merging

2017-01-15 17:20 UTC, wesm commented
Thank you for the contribution