ARROW-378: Python: Respect timezone on conversion of Pandas datetime columns
apache/arrow pull request #287
Opened 2017-01-14 06:47 UTC by ahnj

arrow is now pandas datetime timezone aware

2017-01-14 20:22 UTC, wesm requested changes

2017-01-14 20:22 UTC, wesm commented on python/pyarrow/array.pyx
> +        utc_series_values = utc_series_values.astype('datetime64[ms]')
To my knowledge, all pandas data having a time zone is UTC -- if data is time zone naive, then we may assume UTC in Arrow. I don't think any conversions are necessary here

2017-01-14 20:22 UTC, wesm commented on python/pyarrow/array.pyx
> +        timestamps will be auto-converted to UTC since Arrow only stores in this timezone
It would be better to put this in a `Notes` section, or in the Sphinx documentation

2017-01-14 20:22 UTC, wesm commented on python/pyarrow/tests/test_convert_pandas.py
> +        df_est = df['datetime64'].dt.tz_localize('UTC').dt.tz_convert('US/Eastern').to_frame()
From my comment above, you can look at `x.values.view(np.int64)` before and after `tz_convert('US/Eastern')` to check that the internal values are not modified. If you localize with a non-UTC timestamp, that actually changes the values

2017-01-14 20:22 UTC, wesm commented on python/pyarrow/tests/test_convert_pandas.py
> +        self._check_pandas_roundtrip(df_est, expected=df_est_in_utc, timestamps_to_ms=False)
Can you combine the null and non-null test case?

2017-01-19 22:20 UTC, wesm requested changes
Can you rebase? Thanks

2017-01-19 22:20 UTC, wesm commented on python/pyarrow/array.pyx
> +        else series.dt.tz_convert('UTC')
I still don't believe this is necessary. 

```python
In [11]: dr = pd.date_range('2000-01-01', periods=10)

In [12]: dr_utc = dr.tz_localize('UTC')

In [13]: dr_utc.values.view(np.int64)
Out[13]: 
array([946684800000000000, 946771200000000000, 946857600000000000,
       946944000000000000, 947030400000000000, 947116800000000000,
       947203200000000000, 947289600000000000, 947376000000000000,
       947462400000000000])

In [14]: dr_utc.tz_convert('US/Eastern').values.view(np.int64)
Out[14]: 
array([946684800000000000, 946771200000000000, 946857600000000000,
       946944000000000000, 947030400000000000, 947116800000000000,
       947203200000000000, 947289600000000000, 947376000000000000,
       947462400000000000])
```

2017-01-20 04:37 UTC, ahnj commented on python/pyarrow/array.pyx
> +        else series.dt.tz_convert('UTC')
Oops..  now I see what you mean!  let me go back and fix, and re-rebase.

2017-01-20 17:44 UTC, wesm commented
I left a comment on https://issues.apache.org/jira/browse/ARROW-378

2017-01-22 17:06 UTC, wesm commented on python/pyarrow/array.pyx
> +                pyarrow.get_memory_pool(), utc_series_values, mask, &out))
Can you revert the code changes in this function?

2017-01-22 17:06 UTC, wesm commented on python/pyarrow/array.pyx
> +    function series_as_ndarray() performs the implicit conversion to UTC.
Can you revise to say "Localized timestamps will currently be returned as UTC (pandas's native representation). Timezone-naive data will be implicitly interpreted as UTC".

2017-01-22 21:51 UTC, ahnj commented on python/pyarrow/array.pyx
> +    function series_as_ndarray() performs the implicit conversion to UTC.
Revised with suggested note.

2017-01-22 21:51 UTC, ahnj commented on python/pyarrow/array.pyx
> +                pyarrow.get_memory_pool(), utc_series_values, mask, &out))
Reverted and rebased.  Thanks.

2017-01-22 21:57 UTC, wesm commented
@ahnj can you rebase on the the lastest master? this is based on a commit from 10 days ago https://github.com/ahnj/arrow/commits/timestamp-aware

2017-01-24 03:55 UTC, ahnj commented
rebased with the latest master.

2017-01-24 04:44 UTC, wesm approved these changes
+1. Thank you for the patience!

2017-01-24 04:44 UTC, closed without merging