GH-34410: [Python] Allow chunk sizes larger than the default to be used
apache/arrow pull request #34435
Opened 2023-03-03 17:48 UTC by westonpace

### Rationale for this change

We changed the default chunk size from 64Mi rows to 1Mi rows.  However, it turns out that this property was being treated not just as the default but also as the absolute max.  So it was no longer possible to specify chunk sizes larger than 1Mi rows.  This change separates those two things and restores the max to 64Mi rows.

### What changes are included in this PR?

Pyarrow will now set the `ParquetWriterProperties::max_row_group_length` to 64Mi when constructing a parquet writer.

### Are these changes tested?

Yes.  Unit tests are added.

### Are there any user-facing changes?

No.  The previous change #34281 changed two defaults (absolute max and default).  This PR restores the absolute max back to what it was before.  So it is removing a user-facing change.

2023-03-06 17:51 UTC, wjones127 requested changes
Overall looks good. One suggestion.

2023-03-06 17:51 UTC, wjones127 commented on python/pyarrow/tests/parquet/test_parquet_writer.py
> +@pytest.mark.pandas
Perhaps also:

```suggestion
@pytest.mark.large_memory
@pytest.mark.pandas
```

2023-03-06 21:21 UTC, westonpace commented on python/pyarrow/tests/parquet/test_parquet_writer.py
> +@pytest.mark.pandas
Good idea

2023-03-06 22:36 UTC, wjones127 approved these changes

2023-03-06 23:09 UTC, merged

2023-06-09 04:48 UTC, mapleFU commented on python/pyarrow/_parquet.pyx
> +    props.max_row_group_length(64*1024*1024)
does this causing the bug in https://github.com/apache/arrow/issues/35859#issuecomment-1583614922 ?