GH-35571: [C++][CI][Parquet] adding comparing logs in Decryption tests
apache/arrow pull request #35605
Opened 2023-05-16 03:07 UTC by mapleFU

### Rationale for this change

CI would failed in Decrypt test in Windows MinGW.

### What changes are included in this PR?

Currently add some logs to debug

### Are these changes tested?

No

### Are there any user-facing changes?

No

2023-05-16 04:25 UTC, mapleFU commented
```
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:343: Failure
Expected equality of these values:
  expected_column_data.values[i]
    Which is: 19.8
  read_col_data.values[i]
    Which is: 19.8
values at index 18 not equal read is 19.800001, expect 19.799999
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:343: Failure
Expected equality of these values:
  expected_column_data.values[i]
    Which is: 25.3
  read_col_data.values[i]
    Which is: 25.3
values at index 23 not equal read is 25.300001, expect 25.299999
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:343: Failure
Expected equality of these values:
  expected_column_data.values[i]
    Which is: 26.4
  read_col_data.values[i]
    Which is: 26.4
values at index 24 not equal read is 26.400002, expect 26.400000
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:343: Failure
Expected equality of these values:
  expected_column_data.values[i]
    Which is: 30.8
  read_col_data.values[i]
    Which is: 30.8
values at index 28 not equal read is 30.800001, expect 30.799999
```

I guess the problem comes from floating point equality. @felipecrv

2023-05-16 06:44 UTC, mapleFU commented
Another problem occured when casting decimal to string:

```
[----------] 2 tests from TestDecimalFromReal/1, where TypeParam = std::pair<arrow::Decimal128, double>
[ RUN      ] TestDecimalFromReal/1.TestSuccess
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "4611686000000000000"
  expected
    Which is: "4611686018427387904"
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "-4611686000000000000"
  expected
    Which is: "-4611686018427387904"
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "9223372000000000000"
  expected
    Which is: "9223372036854775808"
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "-9223372000000000000"
  expected
    Which is: "-9223372036854775808"
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "18446744000000000000"
  expected
    Which is: "18446744073709551616"
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "-18446744000000000000"
  expected
    Which is: "-18446744073709551616"
[  FAILED  ] TestDecimalFromReal/1.TestSuccess, where TypeParam = std::pair<arrow::Decimal128, double> (0 ms)
[ RUN      ] TestDecimalFromReal/1.TestErrors
[       OK ] TestDecimalFromReal/1.TestErrors (0 ms)
[----------] 2 tests from TestDecimalFromReal/1 (0 ms total)

[----------] 2 tests from TestDecimalFromReal/2, where TypeParam = std::pair<arrow::Decimal256, float>
[ RUN      ] TestDecimalFromReal/2.TestSuccess
[       OK ] TestDecimalFromReal/2.TestSuccess (0 ms)
[ RUN      ] TestDecimalFromReal/2.TestErrors
[       OK ] TestDecimalFromReal/2.TestErrors (0 ms)
[----------] 2 tests from TestDecimalFromReal/2 (0 ms total)

[----------] 2 tests from TestDecimalFromReal/3, where TypeParam = std::pair<arrow::Decimal256, double>
[ RUN      ] TestDecimalFromReal/3.TestSuccess
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "4611686000000000000"
  expected
    Which is: "4611686018427387904"
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "-4611686000000000000"
  expected
    Which is: "-4611686018427387904"
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "9223372000000000000"
  expected
    Which is: "9223372036854775808"
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "-9223372000000000000"
  expected
    Which is: "-9223372036854775808"
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "18446744000000000000"
  expected
    Which is: "18446744073709551616"
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "-18446744000000000000"
  expected
    Which is: "-18446744073709551616"
[  FAILED  ] TestDecimalFromReal/3.TestSuccess, where TypeParam = std::pair<arrow::Decimal256, double> (0 ms)
[ RUN      ] TestDecimalFromReal/3.TestErrors
```


I gothrough the related code.

2023-05-16 06:49 UTC, mapleFU commented
@pitrou @wjones127 Would you mind take a look at this fixing?

2023-05-16 08:32 UTC, pitrou commented
```
values at index 28 not equal read is 30.800001, expect 30.799999
```

This is not right. Reading Parquet values should be bit-precise, not approximate.

2023-05-16 08:39 UTC, mapleFU commented
I guess the error and https://github.com/apache/arrow/issues/35606 have same underlying reason. Maybe there is some prevision loss in MinGW

2023-05-16 09:02 UTC, pitrou commented
There shouldn't be any precision loss simply when copying values. Perhaps the tests are doing something wrong.

2023-05-16 09:18 UTC, mapleFU commented
Got it, I'm at office and didn't have a Windows machine, I'll try to reproduce it later after I'm home

2023-05-16 13:03 UTC, felipecrv commented
> There shouldn't be any precision loss simply when copying values. Perhaps the tests are doing something wrong.

Could this be tracked in a separate issue and the CI fix merged sooner rather than later?

2023-05-16 13:24 UTC, pitrou commented
Rather than complicating the test routine, I'd rather generate data that doesn't trigger truncation issues (wherever they might happen):
```diff
diff --git a/cpp/src/parquet/encryption/test_encryption_util.cc b/cpp/src/parquet/encryption/test_encryption_util.cc
index 012712c7b..8193e6525 100644
--- a/cpp/src/parquet/encryption/test_encryption_util.cc
+++ b/cpp/src/parquet/encryption/test_encryption_util.cc
@@ -143,7 +143,7 @@ template <>
 ColumnData<FloatType> GenerateSampleData<FloatType>(int rows) {
   ColumnData<FloatType> float_col;
   for (int i = 0; i < rows; i++) {
-    float value = static_cast<float>(i) * 1.1f;
+    float value = static_cast<float>(i) * 1.5f;
     float_col.values.push_back(value);
   }
   return float_col;
```

2023-05-16 14:57 UTC, mapleFU commented
I guess MinGW with unstable CI may generate or truncate data when getting `GenerateSampleData`, so I guess previous fixing in https://github.com/apache/arrow/pull/35605/commits/6265cc17f8b35501f793d3f3c25a972e2ecd2841 is ok
@pitrou What would you think of this?

2023-05-16 16:16 UTC, pitrou commented
> https://github.com/apache/parquet-testing/tree/master/data The data is already here, I guess maybe it cannot help?

Ahaha! Well, that explains why there might be a discrepancy then...

2023-05-16 16:26 UTC, pitrou requested changes

2023-05-16 16:26 UTC, pitrou commented on cpp/src/parquet/encryption/test_encryption_util.cc
> +    ASSERT_EQ(col_md->num_values(), rows_read);
This should be done always, not only for non-floating-point values.
Also, you still need to compare values for non-floating-point.

2023-05-16 16:26 UTC, pitrou commented on cpp/src/parquet/encryption/test_encryption_util.cc
> +      if (std::isnan(expected_column_data.values[i])) {
There doesn't seem to be any NaN in the generated data, this can be removed.

2023-05-17 02:11 UTC, mapleFU commented
Comment fixed. The case here ( https://github.com/apache/arrow/pull/35605#issuecomment-1549078718 ) need to be fixed later, so "C++ / AMD64 Windows MinGW MINGW64 C++" still failed

2023-05-17 02:11 UTC, mapleFU commented
Comment fixed. The case here ( https://github.com/apache/arrow/pull/35605#issuecomment-1549078718 ) need to be fixed later, so "C++ / AMD64 Windows MinGW MINGW64 C++" still failed

2023-05-17 14:18 UTC, merged