GH-35686:[Go] Add AppendTime to TimestampBuilder
apache/arrow pull request #35687
Opened 2023-05-19 10:44 UTC by yevgenypats

### Rationale for this change

### What changes are included in this PR?

### Are these changes tested?

### Are there any user-facing changes?

2023-05-19 15:45 UTC, zeroshade requested changes
Please include the updates to the tmpl files also. 

Otherwise this LGTM, though it would be good to add tests for all the unit types, not just for `Second`.

2023-05-22 15:34 UTC, zeroshade commented
@yevgenypats Do we want to expand the tests to test more units than just `Second`? Or do you think we're fine with just testing `Second`?

2023-05-22 17:30 UTC, yevgenypats commented
> @yevgenypats Do we want to expand the tests to test more units than just `Second`? Or do you think we're fine with just testing `Second`?

I can add but maybe we want to move TimestampBuilder out of the template as it becomes quite hard to develop inside a template and Timestamp starts to diverge from all other numeric types. wdyt?

2023-05-22 17:45 UTC, zeroshade commented
@yevgenypats Makes sense to me, feel free to go ahead and do that.

2023-05-25 07:45 UTC, candiduslynx commented
Hi @zeroshade!

I'm overtaking this PR from @yevgenypats.

I've extracted timestamp from numeric gen (array, builder, tests, traits).

Additionally, I propose to introduce a helper func for creation of `arrow.Timestamp` from `time.Time` and `arrow.TimeUnit`.

The logic was tested and introduced in https://github.com/cloudquery/arrow/pull/17 (in this PR: 1689eee0ec81da6e62f545eb06f8f71ed3f69a22).

2023-05-25 08:16 UTC, yevgenypats commented
> Hi @zeroshade!
> 
> I'm overtaking this PR from @yevgenypats.
> 
> I've extracted timestamp from numeric gen (array, builder, tests, traits).
> 
> Additionally, I propose to introduce a helper func for creation of `arrow.Timestamp` from `time.Time` and `arrow.TimeUnit`.
> 
> The logic was tested and introduced in [cloudquery#17](https://github.com/cloudquery/arrow/pull/17) (in this PR: [1689eee](https://github.com/apache/arrow/commit/1689eee0ec81da6e62f545eb06f8f71ed3f69a22)).
> 
> UPD: it seems there's a [flaky](https://github.com/apache/arrow/actions/runs/5077433733/jobs/9120706233?pr=35687#step:5:739) test (`go/arrow/flight/flightsql/driver/driver_test.go:741`, `TestPreparedStatementNoSchema`)

Thanks @candiduslynx !

2023-05-25 14:11 UTC, candiduslynx commented on go/arrow/type_traits_test.go
> +	if !reflect.DeepEqual(b1, b2) {
I just copy-pasted from the generated code. I can fix it here, if you insist.

2023-05-25 14:12 UTC, candiduslynx commented on go/arrow/type_traits_test.go
> +	if !reflect.DeepEqual(b1, b2) {
Done in e57e2ae596a072ec3e0d1da6460f7d21e86cbd55

2023-05-25 14:20 UTC, zeroshade approved these changes
LGTM Thanks!

2023-05-25 14:20 UTC, merged