ARROW-4523: [JS] Add row proxy generation benchmark
apache/arrow pull request #3601
Opened 2019-02-10 20:39 UTC by TheNeuralBit

2019-02-10 20:58 UTC, TheNeuralBit commented on js/src/util/vector.ts
> +    }
Note I had to create separate comparator logic for Rows and Vectors, since `search.constructor != value.constructor` in this approach.

2019-02-10 23:59 UTC, trxcllnt commented
@TheNeuralBit I could be wrong, but this seems like a bigger change than necessary to fix the problem? Isn't the issue with the second argument to `Object.create()` [here](https://github.com/apache/arrow/blob/master/js/src/vector/row.ts#L82)? If so, couldn't we remove the extra property descriptor map, and set `bound.rowIndex=index`?

2019-02-11 01:56 UTC, trxcllnt commented
@TheNeuralBit PR here: https://github.com/TheNeuralBit/arrow/pull/2. I made the internal Row properties to symbols to avoid naming collisions, and switched the `new BoundRow()` constructor invocation back to a bare `Object.create(this)` call, yielding the following results:

Current version of proxy-bench:
```
Table Iterate "tracks":
length: 1000000
 x 6.88 ops/sec ±0.82% (21 runs sampled)
   avg: 145.4ms
   872.4% of a frame @ 60FPS 
```

This PR:
```
Table Iterate "tracks":
length: 1000000
 x 8.36 ops/sec ±1.02% (25 runs sampled)
   avg: 119.58ms
   717.48% of a frame @ 60FPS 
```

2019-02-11 16:50 UTC, TheNeuralBit commented
@trxcllnt yeah that's a fair point, I didn't think to try `Object.create` without the extra property descriptor map - definitely fine switching to that since it's faster!

I still am partial to separating out the `RowProxyGenerator` and the `Row`s themselves though. I think it's less confusing, and also they won't pollute each other with methods that are only relevant for one or the other (e.g. with the `Object.create(this)` approach, `table.get(0).bind` refers to `Row.bind`).

I pushed up some commits to demonstrate it, perf seems comparable:
```
Table Iterate "tracks":
length: 1000000
 x 8.56 ops/sec ±1.15% (25 runs sampled)
   avg: 116.78ms
   700.68% of a frame @ 60FPS
```

Still needs some cleanup and a switch to Symbols if we go with it

2019-02-11 19:11 UTC, trxcllnt requested changes
1. use Symbols for internal names
2. No extra inner Row class generation
3. Update comparator for symbols/clarity

2019-02-12 04:14 UTC, TheNeuralBit commented on js/src/util/vector.ts
> +    }
This is no longer an issue now that there's no inner class

2019-02-12 04:28 UTC, trxcllnt approved these changes

2019-02-12 04:31 UTC, trxcllnt commented
@TheNeuralBit looks good to me :+1:. last question is do we want to benchmark changing the column index lookups as Symbols?

2019-02-13 03:53 UTC, TheNeuralBit commented
I think I'd rather merge this as is, and do that in another PR, I made [ARROW-4551](https://issues.apache.org/jira/browse/ARROW-4551) to track it

2019-02-13 03:55 UTC, closed without merging