ARROW-4622: WIP: [C++][Python][GLib] MakeDense and MakeSparse in UnionArray should accept a vector of Field
apache/arrow pull request #3723
Opened 2019-02-21 02:52 UTC by mrkn

2019-02-27 00:40 UTC, mrkn commented
The reason of the CI failure is same as https://github.com/apache/arrow/pull/3760

2019-02-27 08:52 UTC, mrkn commented
I think this pull-request is ready for review.

2019-03-01 09:36 UTC, kou reviewed
Can we create `arrow::UnionArray::Make()` instead of adding parameters for `union_()` to `MakeDense()` and `MakeSparse()`?

```cpp
static Status Make(const std::shared_ptr<DataType>& type,
                   const Array& type_ids,
                   const Array& value_offsets,
                   const std::vector<std::shared_ptr<Array>>& children,
                   std::shared_ptr<Array>* out);
```

I think that adding parameters for `union_()` to `MakeDense()` and `MakeSparse()` causes dirty API. If we accept `UnionType` directly, we can improve API by just improving `UnionType` API.

Other C++ developers, what do you think about this?

2019-03-01 10:21 UTC, mrkn commented
@kou 

> Can we create `arrow::UnionArray::Make()` instead of adding parameters for `union_()` to `MakeDense()` and `MakeSparse()`?

My understanding of what you mean is:

1. the changes for MakeDense and MakeSparse should be reverted
2. we should add UnionType::Make so that we can create UnionArray by the code like below:

```cpp
arrow::UnionArray array;
auto array_type = arrow::union_(children, field_names, type_codes, UnionMode::SPARSE);
arrow::UnionArray::Make(array_type, type_ids, value_offsets, children, &array);
```

Is this interpretation correct?

2019-03-01 20:39 UTC, kou commented
Yes. It's what I suggest.

2019-03-12 12:06 UTC, mrkn commented
@wesm @pitrou @fsaintjacques How do you think about this PR?

2019-03-12 13:46 UTC, fsaintjacques commented
I'll give a look.

2019-03-22 23:34 UTC, pitrou commented
@mrkn It looks ok on the principle. Can you rebase on latest master?

2019-03-23 00:28 UTC, mrkn commented
@pitrou I've rebased the branch onto the latest master, and fixed against two kou's comments.

I haven't added `arrow::UnionArray::Make` kou suggested, but I'd like to do it if the suggested approach is better than my approach.

2019-03-25 14:03 UTC, pitrou commented
@mrkn Are you sure the rebase is ok? There seem to be some Rust conflicts...
Once the rebase is fixed, I'll take a look. Thank you :-)

2019-03-25 15:02 UTC, mrkn commented
@pitrou Rebased.

2019-03-25 17:21 UTC, pitrou requested changes
I can't comment on the glib or Ruby changes... Perhaps it's easier to make separate PRs for C++/Python and the rest?

2019-03-25 17:21 UTC, pitrou commented on python/pyarrow/tests/test_array.py
> +def test_union_from_dense_with_field_name():
Is it possible to consolidate all these tests? They don't differ by much...

2019-03-25 17:21 UTC, pitrou commented on python/pyarrow/array.pxi
> +        cdef vector[c_string] fn
Call this `c_field_names`?

2019-03-25 17:21 UTC, pitrou commented on python/pyarrow/array.pxi
> +        cdef vector[uint8_t] tc
Call this `c_type_codes`?

2019-03-25 17:21 UTC, pitrou commented on cpp/src/arrow/union_array-test.cc
> +        compute::_MakeArray<Int8Type, int8_t>(int8(), {0, 1, 2, 0, 1, 3, 2, 0, 2, 1}, {});
You should take a look at `ArrayFromJSON`. It generally makes writing such code easier.

2019-03-25 17:21 UTC, pitrou commented on cpp/src/arrow/union_array-test.cc
> +#include "arrow/compute/test-util.h"
We shouldn't depend on `compute` utilities here.

2019-03-25 17:21 UTC, pitrou commented on cpp/src/arrow/union_array-test.cc
> +TEST_F(TestUnionArray, MakeDenseWithFieldNamesTest) {
Isn't there a way to condensate all these tests?

2019-03-26 06:50 UTC, mrkn commented
> Perhaps it's easier to make separate PRs for C++/Python and the rest?

@pitrou OK. I'll separate GLib and Ruby changes into a different pull request.

2019-04-09 17:20 UTC, pitrou approved these changes

2019-04-09 17:21 UTC, pitrou commented
Thanks @mrkn. The CI failures are unrelated (see ARROW-5148). I will make a few changes and then merge.

2019-04-09 18:33 UTC, closed without merging