GH-34909: [C++] Avoid mean overflow on large integer inputs
apache/arrow pull request #37243
Opened 2023-08-18 10:49 UTC by js8544

### Rationale for this change

The `mean` aggregate function would overflow if the input array's sum is larger than int64_max.

### What changes are included in this PR?

Store intermediate sum in double instead of int64, so that it won't overflow.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.

2023-08-24 05:45 UTC, Light-City commented
In the current implementation, the overflow problem is not considered

2023-08-24 05:48 UTC, Light-City commented
> In the current implementation, the overflow problem is not considered

just like:

```
  func = std::make_shared<ScalarAggregateFunction>("sum", Arity::Unary(), sum_doc,
                                                   &default_scalar_aggregate_options);
  AddArrayScalarAggKernels(SumInit, {boolean()}, uint64(), func.get());
  AddAggKernel(KernelSignature::Make({Type::DECIMAL128}, FirstType), SumInit, func.get(),
               SimdLevel::NONE);
  AddAggKernel(KernelSignature::Make({Type::DECIMAL256}, FirstType), SumInit, func.get(),
               SimdLevel::NONE);
  AddArrayScalarAggKernels(SumInit, SignedIntTypes(), int64(), func.get());
```

sum(int64)-> output also is int64(), will cause overflow.

2023-08-24 06:06 UTC, js8544 commented
What you said is correct. However, this PR is intended to deal with the `mean` function, not `sum`. I'll add a `sum_checked` function after this PR is merged.

2023-08-30 08:48 UTC, pitrou requested changes
One more comment. Also, can you rebase/merge from main?

2023-08-30 08:48 UTC, pitrou commented on cpp/src/arrow/compute/kernels/aggregate_basic_internal.h
> +    : public SumImpl<ArrowType, SimdLevel, DoubleType> {
Can you add a comment above explaining that you're overriding the sum result type and why?

2023-08-30 16:03 UTC, pitrou approved these changes

2023-08-30 16:03 UTC, merged

2023-08-30 16:03 UTC, pitrou commented
Thank you @js8544 !