GH-37290: [MATLAB] Add `arrow.array.Time32Array` class
apache/arrow pull request #37315
Opened 2023-08-22 18:08 UTC by sgilmore10

### Rationale for this change

Now that `arrow.type.Time32Type` class has been added to the MATLAB Interface (#37250), we can add the `arrow.array.Time32Array` class. 

### What changes are included in this PR?

1. Added a new class `arrow.array.Time32Array`. It has the following read-only properties: `Type` and `Length`. It has the following methods: `fromMATLAB()`, `toMATLAB()`, and `duration()`.
2. Added a new class called `arrow.type.traits.Time32Traits`.

**Example Usage**

```matlab
>> times = seconds([100 120 NaN 200])

times = 

  1×4 duration array

   100 sec   120 sec   NaN sec   200 sec

>> time32Array = arrow.array.Time32Array.fromMATLAB(times)

time32Array = 

[
  00:01:40,
  00:02:00,
  null,
  00:03:20
]

>> roundtrip = toMATLAB(time32Array)

roundtrip = 

  4×1 duration array

   100 sec
   120 sec
   NaN sec
   200 sec

```

You can also specify the `TimeUnit` to use via a name-value pair. `TimeUnit` can either be `"Second"`  (default) or `"Milisecond"`.

```matlab
>> times = seconds([100 120 NaN 200]);
>> time32Array = arrow.array.Time32Array.fromMATLAB(times, TimeUnit="Millisecond")

time32Array = 

[
  00:01:40.000,
  00:02:00.000,
  null,
  00:03:20.000
]
```

### Are these changes tested?

Yes. Added two new test classes: `tTime32Array.m` and `tTime32Traits.m`.

### Are there any user-facing changes?

Yes, users can now create `arrow.array.Time32Array`s from MATLAB `duration`s via the static `fromMATLAB` method on `arrow.array.Time32Array`.

### Future Directions

1. Add `arrow.array.Time64Array`
2. Add `arrow.type.Date32Type` and `arrow.array.Date32Array`
3. Add `arrow.type.Date64Type` and `arrow.array.Date64Array`

2023-08-22 19:42 UTC, kevingurney requested changes
Looks good overall - thank you!

2023-08-22 19:42 UTC, kevingurney commented on matlab/test/arrow/array/tTime32Array.m
> +            % expected by InferNulls=true is provided.
by -> when

2023-08-22 19:42 UTC, kevingurney commented on matlab/test/arrow/array/tTime32Array.m
> +            % expected by InferNulls=false is provided.
by -> when

2023-08-22 19:42 UTC, kevingurney commented on matlab/test/arrow/array/tTime32Array.m
> +            % test with NDimensional empty array
Just a slight wording change suggestion: "Test with an N-Dimensional empty array"

2023-08-22 20:01 UTC, sgilmore10 commented on matlab/src/cpp/arrow/matlab/array/proxy/time32_array.cc
> +       auto data_buffer = std::make_shared<MatlabBuffer>(timestamp_mda);
Good catch!

2023-08-22 20:08 UTC, sgilmore10 commented on matlab/src/matlab/+arrow/+array/Time32Array.m
> +            time = Time32Array.convertDurationToNumber(data, opts.TimeUnit);
I'll change the name!

2023-08-23 02:49 UTC, kou approved these changes
+1

2023-08-23 02:49 UTC, merged