GH-37434: [C++] IO: Refactor BufferedInputStream for small input
apache/arrow pull request #37460
Opened 2023-08-30 10:08 UTC by mapleFU

### Rationale for this change

If we Set BufferSize == 100k, and read 3k bytes per IO. When we read the 34 times, the IO would be (99k, 102k]

In Read, it will read buffered (99k, 100k], issue IO for (100k, 102k]. Rather than (100k, 200k]. 

### What changes are included in this PR?

Refactor `BufferedInputStream::Read` to optimize small IO.

### Are these changes tested?

Already has tests?

### Are there any user-facing changes?

User might get io-pattern changed. It can be optimization or downgrade.

2023-08-30 11:27 UTC, mapleFU commented
cc @pitrou @lidavidm Would you mind take a look?

2023-08-30 12:38 UTC, pitrou requested changes
Thanks @mapleFU ! This looks good on the principle. Some comments below.

Also, perhaps we can add tests for this? `TrackedRandomAccessFile` allows recording the exact Read calls on the raw stream, so you can easily check the different read patterns.

2023-08-30 12:38 UTC, pitrou commented on cpp/src/arrow/io/buffered.cc
> +    int64_t remain_bytes = nbytes - pre_buffer_copy_bytes;
Nit: call this `remaining_bytes`

2023-08-30 12:38 UTC, pitrou commented on cpp/src/arrow/io/buffered.cc
> +    // 1. First consume pre-buffered data.
Should you first ensure that `nbytes` does not go past `raw_read_bound_`?

2023-08-30 15:20 UTC, mapleFU commented
@pitrou I've added some tests and fix the bound

2023-08-31 13:07 UTC, pitrou commented on cpp/src/arrow/io/buffered_test.cc
> +  EXPECT_EQ(6, tracked_->bytes_read());
We could instead check the exact read ranges (untested):
```suggestion
  EXPECT_EQ(0, buffered_->bytes_buffered());
  EXPECT_EQ(tracked_->get_read_ranges(), {ReadRange{0, 6}});
```

2023-08-31 13:08 UTC, pitrou commented on cpp/src/arrow/io/buffered_test.cc
> +  EXPECT_EQ(6, tracked_->bytes_read());
Same suggestion below.

2023-08-31 13:11 UTC, pitrou commented on cpp/src/arrow/io/buffered.cc
>      }
This check can be removed if you rework the logic below a bit:
```c++
    DCHECK_EQ(0, bytes_buffered_);
    if (raw_read_bound_ >= 0) {
      remaining_bytes = std::min(remaining_bytes, raw_read_bound_ - raw_read_total_);
    }
    if (remaining_bytes == 0) {
      return pre_buffer_copy_bytes;
    }
```

2023-08-31 13:12 UTC, pitrou commented on cpp/src/arrow/io/buffered.cc
> +    if (remaining_bytes > buffer_size_) {
Nit: no need to fill the buffer if we are going to exhaust it entirely
```suggestion
    if (remaining_bytes >= buffer_size_) {
```

2023-08-31 16:43 UTC, pitrou approved these changes

2023-08-31 16:44 UTC, pitrou commented
I've added some random tests and also expanded the existing tests a bit. I'll merge if CI is green.

2023-08-31 16:44 UTC, pitrou commented
@githutb-actions crossbow submit -g cpp

2023-08-31 17:03 UTC, pitrou commented
@githutb-actions crossbow submit -g cpp

2023-08-31 17:03 UTC, pitrou commented
@github-actions crossbow submit -g cpp

2023-08-31 18:44 UTC, merged