GH-37626: [Java][Cpp] support using existing java file system
apache/arrow pull request #37690
Opened 2023-09-13 07:35 UTC by zinking

### Rationale for this change

when using the dataset api to repeatedly read chunks of file, FileSystem instances are created every time. causing performance degrade.

### What changes are included in this PR?

to reuse existing filesystem passed from java context.

### Are these changes tested?

tested on my local integration. as there seems no end to end dataset testing in the base

### Are there any user-facing changes?
NO

2023-09-13 11:59 UTC, lidavidm commented
I think what we'd want is to add a FileSystem parameter to FileSystemDatasetFactory::Make or FileSystemFactoryOptions, instead of a global.

2023-09-13 12:11 UTC, zinking commented
> I think what we'd want is to add a FileSystem parameter to FileSystemDatasetFactory::Make or FileSystemFactoryOptions, instead of a global.

hmm, maybe just the naming, it is a field in FileSystemFactoryOptions and then passed down not a global variable.

2023-09-13 12:40 UTC, lidavidm commented
Ah, sorry. In that case it should be named something less Java-specific and should probably be typed `std::shared_ptr<FileSystem>`? You can use [`PathFromUri`](https://github.com/apache/arrow/blob/4fac528e2ee9c4efce453420275cbaf0b3b6adb0/cpp/src/arrow/filesystem/filesystem.h#L192) to validate that the filesystem is compatible with the given URI

2023-09-15 17:16 UTC, lidavidm requested changes

2023-09-15 17:16 UTC, lidavidm commented on cpp/src/arrow/dataset/discovery.h
> +  std::shared_ptr<void> file_system_java = nullptr;
I don't think this needs to be Java-specific at all.

This should be `shared_ptr<FileSystem>`.

2023-09-15 17:16 UTC, lidavidm commented on cpp/src/arrow/dataset/discovery.cc
> +                        fs::FileSystemFromUriAndFs(uri, &internal_path, options.file_system_java))
I think what you would do is, if a filesystem is provided, call FileSystem::PathFromUri to set `internal_path`. If it succeeds, then proceed, else raise an error.

2023-09-27 16:45 UTC, westonpace requested changes
The change (allowing a filesystem to be specified when running discovery) seems good.  I agree with @lidavidm that this shouldn't be java-specific.

2025-12-19 18:22 UTC, thisisnic commented
Closing this now that the Java implementation has moved to: https://github.com/apache/arrow-java

2025-12-19 18:22 UTC, closed without merging