GH-38164: [MATLAB] Rename `Length` property on `arrow.array.Array` and  `arrow.array.ChunkedArray` to `NumElements`
apache/arrow pull request #38190
Opened 2023-10-10 20:04 UTC by sgilmore10

### Rationale for this change

We would like to rename the `Length` property on `arrow.array.Array` (and `arrow.array.ChunkedArray`) to `NumElements` because MATLAB has a function called `length(A)`, which returns the length of the largest array dimension in `A`.  
Because `arrow.array.Array` inherits from `matlab.mixin.Scalar`, it's size is always `1x1`, so the `length()` function always returns `1`. This may confuse users because the `Length` property of `arrow.array.Array` returns the number of elements within the array, which may not be `1`. 

```matlab
>>  array = arrow.array([1 2 3 4 5]);

% The length property returns the number of elements in the array
>> array.Length

ans =

  int64

   5

% The length method returns the length of the largest dimension
>> length(array)

ans =

     1
```

I suspect this inconsistency will confuse users, so we should rename the `Length` property to `NumElements`. 

### What changes are included in this PR?

1. Renamed `Length` property on `arrow.array.Array` to `NumElements`
2. Renamed `Length` property on `arrow.array.ChunkedArray` to `NumElements`

### Are these changes tested?

Yes. I modified the existing `Length` tests cases to now test the `NumElements` property.

### Are there any user-facing changes?

Yes. Please note this is a breaking change because `Length` is no longer a property on either `arrow.array.Array` or `arrow.array.ChunkedArray`. However, we have not yet cut an initial release of the MATLAB interface, so we don't expect this change should affect too many users at this point.

2023-10-10 20:57 UTC, kevingurney requested changes
Thank you for making this change! This is a nice usability improvement and should hopefully reduce unnecessary confusion.

2023-10-10 20:57 UTC, kevingurney commented on matlab/src/matlab/+arrow/+tabular/+internal/validateArrayLengths.m
> +            msg = compose("Expected all arrays to %d elements," + ...
to *have* %d elements

2023-10-10 20:57 UTC, kevingurney commented on matlab/test/arrow/array/tChunkedArray.m
> +            % ChunkedArray with three chunks and nonzero at least one element
nonzero at least on element -> at least one element

2023-10-11 00:46 UTC, kou approved these changes
+1

2023-10-11 13:32 UTC, sgilmore10 commented on matlab/src/matlab/+arrow/+tabular/+internal/validateArrayLengths.m
> +            msg = compose("Expected all arrays to %d elements," + ...
ah good catch!

2023-10-11 13:46 UTC, kevingurney approved these changes

2023-10-11 13:56 UTC, merged