GH-34890: [C++][Python] Add a no-op kernel for dictionary_encode(dictionary)
apache/arrow pull request #38349
Opened 2023-10-19 14:27 UTC by js8544

Added a no-op kernel for convenience as discussed in the issue.

2023-10-19 14:28 UTC, js8544 commented
cc @jorisvandenbossche

2023-10-26 14:39 UTC, bkietz requested changes
Minor formatting nit, otherwise this looks good

2023-10-26 14:39 UTC, bkietz commented on docs/source/cpp/compute.rst
> +a Dictionary array.
```suggestion
* \(1) Output is ``Dictionary(Int32, input type)``. It is a no-op if input is
  a Dictionary array.
```

2023-10-27 07:43 UTC, jorisvandenbossche approved these changes
Looks good, thanks!

2023-10-27 07:43 UTC, jorisvandenbossche commented on cpp/src/arrow/compute/kernels/vector_hash.cc
> +     "This function does nothing if the input is already a dictionary."),
```suggestion
     "This function does nothing if the input is already a dictionary array."),
```

2023-10-27 13:01 UTC, bkietz approved these changes

2023-12-09 16:23 UTC, js8544 commented
@jorisvandenbossche @bkietz Hi guys, would you mind merging this PR?

2023-12-11 17:00 UTC, bkietz commented
Sorry, lost track of this

2023-12-11 17:01 UTC, merged