GH-39131: [JS] Add at() for array like types
apache/arrow pull request #40712
Opened 2024-03-21 14:51 UTC by domoritz

Arrays in JavaScript have `at` instead of `get` so here we are making our arrays more consistent.

2024-03-21 16:57 UTC, domoritz commented
@trxcllnt and I agreed offline to wrap indexes accesses so that any index is valid. The behavior in js is to only index -length ... length and return undefined otherwise but that seems less consistent than to just always wrap. Also, the types can be composer since we never return undefined.

2024-03-21 22:18 UTC, trxcllnt requested changes
-1 for renaming `get()` to `at()`. I'm fine adding `at()`, but `get()` and `set()` are equivalent to accessing an element by subscript index, e.g. `x = xs[0]` and `xs[0] = x`.

We've tried to get rid of them in the past in favor of proxies, but they're still the fastest way to access elements besides enumerating the binary data directly.

2024-03-21 23:51 UTC, domoritz commented
I see. So you are saying we should keep the get visitor and just make `at` a method that calls `get`?

Isn't `at` as I implemented equivalent to `get` within the valid range of values? Do we want to keep `get` because it's slightly faster than `at`?

2024-03-22 01:41 UTC, domoritz commented
Redone in https://github.com/apache/arrow/pull/40730

2024-03-22 01:41 UTC, closed without merging