GH-41347: [FlightRPC][C#] Change protection levels of classes to support non-Kestreal GRPC flight server
apache/arrow pull request #41348
Opened 2024-04-23 11:14 UTC by qed-

### Rationale for this change

With the existing structure it is not possible to create a flight RPC service as a regular GRPC service, outside of AspNet.Core/Kestrel.

This can be supported by changing the protection level of the generated classes and FlightServiceImplementation.cs 

### What changes are included in this PR?

Change protection level from internal to public for generated protocol files and FlightServiceImplementation.cs

### Are these changes tested?

Confirmed that classes are public in the built assembly.

### Are there any user-facing changes?

Generated protocol classes will become visible to end users.

2024-04-23 21:45 UTC, CurtHagenlocher requested changes
It's a bit unfortunate that we have to expose so many internals to make this work; it creates "upgrade risk" for anyone who happens to take a dependency on the generated classes. Out of curiosity, what's the server or servers you're interested in? Are they likely of wider interest? Could we ship that support as a separate project from this codebase?

Otherwise, I think FlightServerImplementation should be moved to the "Server" namespace and directory as it's clearly no longer "Internal".

2024-04-25 10:11 UTC, qed- commented
Thanks for your comments. My use case is to run a Flight GRPC server on .Net framework (due to it depending on legacy assemblies that don't work with .net core). 

I've modified the PR to move the namespace as you suggested. 

The other option would be to create a public class that implements code similar to the below, happy to do it this way if you think this is a better option.

```
using Apache.Arrow.Flight.Protocol;
using Apache.Arrow.Flight.Server;

var flightServer = new FlightServerImpl();
var server = new Server
{
    Services = {  FlightService.BindService(new FlightServerImplementation(flightServer)) },
    Ports =  { new ServerPort("0.0.0.0", 5001, ServerCredentials.Insecure) }   }
};
server.Start();
```

2024-05-10 07:05 UTC, qed- commented
Hi @CurtHagenlocher, please let me know if you'd like further changes to this PR.

2024-06-17 06:56 UTC, qed- commented
hi @CurtHagenlocher - any feedback on this? Thanks.

2024-07-01 03:24 UTC, CurtHagenlocher commented
I'm very sorry for the delay, @qed; I'd meant to take another look at this before the fork for the next release, but we've now run out of time. Can you say a little more about the other option? What class exactly is "Server" here?

2024-07-01 16:08 UTC, qed- commented
Hi @CurtHagenlocher, no worries.

Server is this class https://grpc.github.io/grpc/csharp/api/Grpc.Core.Server.html

We are using this to run the server on HTTP.sys, due to Kestrel not being available in .Net framework.

2024-07-01 16:54 UTC, CurtHagenlocher commented
Okay, thanks! What if we were to have a separate build target which references Desktop framework and contains a package reference to that older gRPC framework and the code you need to be able to use it? That way, the newer package doesn't pick up a conflicting and unneeded dependency.

2024-07-02 08:30 UTC, qed- commented
Yes I'd be happy with that approach.

2024-07-11 15:53 UTC, qed- commented
@CurtHagenlocher changed as suggested, let me know if you'd like any further changes.

2024-09-14 14:01 UTC, CurtHagenlocher approved these changes

2024-09-14 14:02 UTC, merged