[C++]Fixes compiler warning in recent VS updates
apache/arrow pull request #4213
Opened 2019-04-26 09:15 UTC by LarryIII

Resolve narrowing from wchar_t -> char warning in recent VS updates, this code will cause a C++ compiler warning C4244, so add the fix in your port. Thanks!

warning info: 
~\include\xstring(2308): warning C4244: 'argument': conversion from '_Ty' to 'const _Elem', possible loss of data

2019-04-26 12:22 UTC, fsaintjacques commented
Could you open a corresponding jira issue and title the PR appropriately? This is need to ensure the autogenerated CHANGELOG includes this.

2019-04-26 14:29 UTC, wesm commented
Is this fixed in the upstream code that's being vendored here? Editing vendored files is a slippery slope

2019-04-29 13:17 UTC, pitrou commented
I'm also -1 on editing vendored code like this.

2019-04-30 03:07 UTC, BillyONeal commented on cpp/src/arrow/vendored/datetime/tz.cpp
> +        for (std::size_t idx = 0; idx != wcslen(folder_ptr.get()); ++idx)
This wcslen should be extracted as a separate variable to avoid doing a wcslen on every character.

2019-04-30 03:14 UTC, BillyONeal commented
I created a JIRA issue.... I think, here: https://issues.apache.org/jira/browse/ARROW-5242

2019-04-30 03:15 UTC, BillyONeal commented on cpp/src/arrow/vendored/datetime/tz.cpp
> +        folder.clear();
An alternate workaround would be to `#pragma warning(suppress: 4244) // narrowing wchar_t -> char` here.

2019-04-30 06:04 UTC, LarryIII commented
Thanks all here. Just disable this warning as a workaround here.

2019-04-30 07:00 UTC, pitrou requested changes
The warning signals a genuine error in the code. It was fixed upstream, so we should simply vendor the (unreleased) new version:
https://github.com/HowardHinnant/date/pull/419

2019-04-30 14:03 UTC, wesm commented
ARROW-5242 was just opened about this

2019-06-05 03:19 UTC, wesm commented
Would someone like to update the vendored module?

2019-06-11 18:43 UTC, wesm commented
I'm taking care of it. Closing

2019-06-11 18:43 UTC, closed without merging