ARROW-5224: [Java] Add APIs for supporting directly serialize/deserialize ValueVector
apache/arrow pull request #4280
Opened 2019-05-09 09:13 UTC by tianchen92

related to [ARROW-5224](https://issues.apache.org/jira/browse/ARROW-5224).

There is no API to directly serialize/deserialize ValueVector. The only way to implement this is to put a single FieldVector in VectorSchemaRoot and convert it to ArrowRecordBatch, and the deserialize process is as well. 

Provide a utility class to implement this may be better, I know all serializations should follow IPC format so that data can be shared between different Arrow implementations. But for users who only use Java API and want to do some further optimization, this seem to be no problem and we could provide them a more option.

This may take some benefits for Java user who only use ValueVector rather than IPC series classes such as ArrowReordBatch:

We could do some shuffle optimization such as compression and some encoding algorithm for numerical type which could greatly improve performance.
Do serialize/deserialize with the actual buffer size within vector since the buffer size is power of 2 which is actually bigger than it really need.
Reduce data conversion(VectorSchemaRoot, ArrowRecordBatch etc) to make it user-friendly.

2019-05-13 02:45 UTC, tianchen92 commented
cc @BryanCutler , could you please take a look? thanks

2019-05-13 03:58 UTC, emkornfield requested changes
I left some comments. I'm still not sure this is a change we want to officially support.  @jacques-n  or @siddharthteotia  could you comment.

2019-05-13 03:58 UTC, emkornfield commented on java/vector/src/main/java/org/apache/arrow/vector/util/FieldVectorUtility.java
> +
this should have a private constructor.

2019-05-13 03:58 UTC, emkornfield commented on java/vector/src/main/java/org/apache/arrow/vector/util/FieldVectorUtility.java
> +public class FieldVectorUtility {
I think FieldVectorSerdes or FieldVectorSerdeUtilitiy would be a better name for this class.

2019-05-13 03:58 UTC, emkornfield commented on java/vector/src/test/java/org/apache/arrow/vector/util/TestFieldVectorUtility.java
> +    vector.clear();
are these needed?

2019-05-13 03:58 UTC, emkornfield commented on java/vector/src/test/java/org/apache/arrow/vector/util/TestFieldVectorUtility.java
> +    vector.clear();
are these needed?

2019-05-13 03:58 UTC, emkornfield commented on java/vector/src/main/java/org/apache/arrow/vector/util/FieldVectorUtility.java
> + * Utility class for FieldVector.
please describe the on the wire format this class serializes to and deserializes from (that might also affect the class name).

Please describe that this this isn't part of the official arrow standand.

2019-05-13 03:58 UTC, emkornfield commented on java/vector/src/main/java/org/apache/arrow/vector/util/FieldVectorUtility.java
> +    int validityBufferCapacity = (valueCount + 7) >> 3;
there are already utility methods that have this implementation can you use one of them?

2019-05-13 03:58 UTC, emkornfield commented on java/vector/src/main/java/org/apache/arrow/vector/util/FieldVectorUtility.java
> +      throw new UnsupportedOperationException("Unsupported FieldVector:" + vector.getField().getName());
are there any known limitations here, if so please document in javadoc.

2019-05-13 03:58 UTC, emkornfield commented on java/vector/src/main/java/org/apache/arrow/vector/util/FieldVectorUtility.java
> +  public static void serializeFieldVector(WriteChannel out, FieldVector vector) throws IOException {
javadoc

2019-05-13 03:58 UTC, emkornfield commented on java/vector/src/main/java/org/apache/arrow/vector/util/FieldVectorUtility.java
> +  public static void deserializeFieldVector(ReadChannel in, FieldVector vector) throws IOException {
javadoc.

2019-05-13 03:58 UTC, emkornfield commented on java/vector/src/main/java/org/apache/arrow/vector/util/FieldVectorUtility.java
> +    out.write(reuseIntBytes);
sizeBytes might be a better name for this?

2019-05-13 04:19 UTC, emkornfield commented
I should be more specific.  There shouldn't be a Java only serialization format, as that is against the arrow philosophy if a new communication protocol is desired it should get consensus from the broader community (via a mailing list discussion) that we want to support it across all languages.

2019-05-13 04:36 UTC, tianchen92 commented
@emkornfield Thanks very much for your comments. I know this is not not conforming to Arrow standard format as I described in [ARROW-5224](https://issues.apache.org/jira/browse/ARROW-5224). The inspiration for this comes from our usage of JAVA API, so we would like to provide another option for user to implement this (not in MessageSerializer).
Absolutely it's better to make it a new communication protocol and support all languages, but since it's not very complete for all types and maybe it's hard to add a communication. So before doing this, maybe we could provide a tricky utility in Java which not affect the Arrow standard format. What do you think? Could I resolve the comments mentioned above? Thanks very much.

2019-05-23 17:31 UTC, emkornfield commented
Note: https://issues.apache.org/jira/browse/ARROW-300 covers doing compression on buffers, maybe you can propose something there?

2019-05-24 01:47 UTC, tianchen92 commented
@emkornfield Got it, thanks for your kind reminder.

2019-06-03 02:32 UTC, closed without merging