ARROW-5311: [C++] use more specific error status types in take
apache/arrow pull request #4317
Opened 2019-05-15 13:40 UTC by bkietz

Now emits

- TypeError when indices are not integral
- KeyError when an index is out of bounds

2019-05-15 13:46 UTC, jorisvandenbossche commented
@bkietz you will probably need to update the python test to change ValueError in TypeError here: https://github.com/apache/arrow/blob/master/python/pyarrow/tests/test_compute.py#L93 (and the ValueError to KeyError in the two out of bounds cases a bit higher in the file)

2019-05-15 14:13 UTC, bkietz commented
@jorisvandenbossche thanks, good catch

2019-05-15 14:38 UTC, pitrou requested changes
I've rather have a dedicated `IndexError` for out-of-bounds issues.

2019-05-16 09:10 UTC, jorisvandenbossche commented on cpp/src/arrow/status.h
> +  /// Return an error status when a container's capacity would exceed its limits
I suppose this is a left-over from copy paste? (from CapacityError)

2019-05-16 09:47 UTC, pitrou requested changes
Thanks for the update. There is a remaining thing to do: in `ConvertPyError()` (`src/arrow/python/common.cc`), return `StatusCode::IndexError` if the Python exception matches `PyExc_IndexError`.

2019-05-16 11:28 UTC, pitrou approved these changes

2019-05-16 12:42 UTC, pitrou commented
The Java Gandiva failure is unrelated, will merge.

2019-05-16 12:42 UTC, closed without merging

2019-05-16 20:36 UTC, kou commented on c_glib/arrow-glib/error.cpp
> +G_DEFINE_QUARK(garrow - error - quark, garrow_error)
This should not be included spaces around `-`.
`G_DEFINE_QUARK` is a macro. `garrow-error-quark` is used as an identifier.

Arrow GLib doesn't use the same coding style as Arrow C++. So we don't need to use `clang-format`.
I'll send a pull request to revert this change.