GH-38847: [Documentation][C++] Explicitly note that compute is optional
apache/arrow pull request #43629
Opened 2024-08-09 18:01 UTC by bkietz

### Rationale for this change

A user didn't know from reading just the compute documentation that compute is an optional feature. We can make that explicit

### What changes are included in this PR?

Added a cross-reference to the optional features section

### Are these changes tested?

No

### Are there any user-facing changes?

No

2024-08-09 18:51 UTC, amoeba requested changes
Feel free to leave my suggestion for bullet point (1).

2024-08-09 18:51 UTC, amoeba commented on docs/source/cpp/tutorials/compute_tutorial.rst
> +  - Be sure that your arrow installation
```suggestion
  - Be sure that your Arrow installation
```

2024-08-09 18:51 UTC, amoeba commented on docs/source/cpp/tutorials/compute_tutorial.rst
> +/cpp/building.html#optional-components
```suggestion
```

Was this added unintentionally?

2024-08-09 18:51 UTC, amoeba commented on docs/source/cpp/tutorials/compute_tutorial.rst
>  1. An Arrow installation, which you can set up here: :doc:`/cpp/build_system`
Maybe just something like this instead?

```suggestion
1. An Arrow installation, which you can set up here: :doc:`/cpp/build_system`. If you're compiling Arrow yourself, be sure you compile with the compute module enabled (i.e., ``-DARROW_COMPUTE=ON``), see
:doc:`Optional Components. <cpp_build_optional_components>` for more information.
```

Then line 45 can be removed.

2024-08-19 13:49 UTC, bkietz commented on docs/source/cpp/tutorials/compute_tutorial.rst
> +/cpp/building.html#optional-components
Yes, thanks!

2024-08-19 14:18 UTC, mapleFU commented
I remember a weird thing that even compute is not enabled, some module of compute (like basic cast) would be compiled. Should we mention this? Or just leave it here?

2024-08-19 16:25 UTC, bkietz commented on docs/source/cpp/tutorials/compute_tutorial.rst
> +   If you're comiling Arrow yourself, be sure you compile with the compute module
argh

2024-08-19 16:26 UTC, bkietz commented
> Should we mention this?

It might be worth documenting, but not in this tutorial since it uses kernels which are not included in that

2024-08-19 16:30 UTC, mapleFU commented
+1 for me

2024-08-19 16:33 UTC, amoeba approved these changes

2024-08-19 16:34 UTC, amoeba commented
LGTM. Thanks @bkietz.

2024-08-19 19:01 UTC, merged