GH-43680: [Integration] Unskip nanoarrow in IPC integration tests
apache/arrow pull request #43715
Opened 2024-08-15 20:03 UTC by bkietz

### Rationale for this change

Nanoarrow can now read and write IPC files as of https://github.com/apache/arrow-nanoarrow/pull/585 so it should no longer be skipped as a producer/consumer

### What changes are included in this PR?

Nanoarrow's tester is updated to point to the new integration executable and to report nanoarrow as a consumer/producer of IPC files.

Notably the `null_trivial` case is skipped even though nanoarrow nominally supports it since it represents a corner case in which nanoarrow's flatbuffers library will not accept some vectors produced by other flatbuffers libraries https://github.com/dvidelabs/flatcc/issues/287

### Are these changes tested?

Yes

### Are there any user-facing changes?

No

2024-08-19 10:19 UTC, pitrou requested changes
Looks like there are a lot of nanoarrow-related failures in the Integration build

2024-08-19 10:19 UTC, pitrou commented on dev/archery/archery/integration/datagen.py
> +        .skip_tester('nanoarrow'),
Can we add issue references for these skips?

2024-09-20 16:59 UTC, bkietz commented
This failure is due to nanoarrow's reliance on [post-0.15 stream continuations](https://github.com/bkietz/arrow/blob/de12a7af86261f82d799c4a9aef840d41ec0886b/docs/source/format/Columnar.rst?plain=1#L1224-L1226)
```
Validating that /home/dewey/gh/arrow/../arrow-testing/data/arrow-ipc-stream/integration/0.14.1/generated_map.arrow_file reads identical to /tmp/tmpej5fzvgi/0.14.1_map.gold.json
Command VALIDATE failed (22=Invalid argument): Expected 0xFFFFFFFF at start of message but found 0x0000011C
```

and this one is because [pre 1.0 unions had null bufffers](https://github.com/bkietz/arrow/blob/de12a7af86261f82d799c4a9aef840d41ec0886b/format/Schema.fbs#L47-L50), which adds one more buffer per union field than we expect
```
Validating that /home/dewey/gh/arrow/../arrow-testing/data/arrow-ipc-stream/integration/0.17.1/generated_union.arrow_file reads identical to /tmp/tmpej5fzvgi/0.17.1_union.gold.json
Command VALIDATE failed (22=Invalid argument): Expected 24 buffers in message but found 28
```

2024-09-24 14:02 UTC, pitrou approved these changes
+1, just a nit

2024-09-24 14:26 UTC, bkietz commented on dev/archery/archery/integration/tester_nanoarrow.py
> +                for q in quirks or ""
:+1: will merge after CI is green again

2024-09-24 16:50 UTC, bkietz commented
CI failure unrelated. Merging

2024-09-24 16:58 UTC, merged

2024-09-24 19:15 UTC, alamb commented
nanoarrow / rust integration tests are failing now it seems: https://github.com/apache/arrow-rs/issues/6448

Do we know if the underlying issue is tracked anywhere?