ARROW-6270: [C++] check buffer_index bounds in IpcComponentSource.GetBuffer
apache/arrow pull request #5105
Opened 2019-08-16 11:59 UTC by crepererum

2019-08-16 16:49 UTC, bkietz requested changes

2019-08-16 16:49 UTC, bkietz commented on cpp/src/arrow/ipc/reader.cc
> +      return Status::IOError("buffer_index out of range.");
I think this should be Status::IndexError

2019-08-16 16:50 UTC, bkietz commented on cpp/src/arrow/ipc/reader.cc
> +      return Status::IOError("buffer_index out of range.");
(Not clang-formatted:)
```suggestion
      return Status::IndexError("buffer_index (", buffer_index, ")out of range; only ", buffers->size(), " buffers are available.");
```

2019-08-17 20:26 UTC, wesm approved these changes
+1. Really this indicates corruption in the data, so I think this is OK. 

We need to get the fuzzer corpus running in CI

2019-08-17 20:27 UTC, closed without merging