ARROW-7542: [CI][C++] Use $(sysctl -n hw.ncpu) instead of $(nproc) on macOS
apache/arrow pull request #6160
Opened 2020-01-10 07:23 UTC by kou

2020-01-10 14:50 UTC, nealrichardson approved these changes
I checked for other places where `nproc` is called and they all have this logic around them (though they look at `uname` to determine OS), all except `cpp/examples/minimal_build/build.sh`. But that one corresponds to a ubuntu dockerfile so it's probably fine.

2020-01-10 15:56 UTC, nealrichardson requested changes
Actually it looks like this doesn't work: all of the C++ test jobs are failing, e.g. https://github.com/apache/arrow/pull/6160/checks?check_run_id=382886347#step:5:1459

Perhaps switch to check uname, like the others?

2020-01-10 21:30 UTC, kou commented on ci/scripts/cpp_test.sh
> +if type nproc > dev/null 2>&1; then
`/` is missing before `dev/null`...

2020-01-10 21:34 UTC, kou commented
Anyway, I changed to use `uname`.

2020-01-11 01:29 UTC, nealrichardson approved these changes
Thanks @kou! I'll merge. The test failures are flaky tests, ticketed https://issues.apache.org/jira/browse/ARROW-7551 and https://issues.apache.org/jira/browse/ARROW-7552

2020-01-11 01:29 UTC, closed without merging