ARROW-5742: [CI][C++] Add nightly Valgrind build
apache/arrow pull request #6329
Opened 2020-01-30 20:14 UTC by pitrou

2020-01-30 20:14 UTC, pitrou commented
@kszucs

2020-01-30 20:22 UTC, pitrou commented
I've checked this runs successfully locally (though slowly):
```
$ docker-compose run --rm conda-cpp-valgrind

[ ... ]

100% tests passed, 0 tests failed out of 78

Label Time Summary:
arrow-tests      = 829.10 sec*proc (60 tests)
arrow_dataset    =  96.69 sec*proc (8 tests)
parquet-tests    = 350.21 sec*proc (7 tests)
plasma-tests     = 147.54 sec*proc (3 tests)
unittest         = 1423.54 sec*proc (78 tests)

Total Test time (real) = 187.49 sec
+ '[' '' == ON ']'
+ popd
/
```

2020-01-31 12:21 UTC, pitrou commented
@ursabot crossbow build test-conda-cpp-valgrind

2020-01-31 12:21 UTC, pitrou commented
@ursabot crossbow help

2020-01-31 12:21 UTC, pitrou commented
@ursabot crossbow test-conda-cpp-valgrind

2020-01-31 12:21 UTC, pitrou commented
@ursabot crossbow test-conda-cpp-valgrind

2020-01-31 12:21 UTC, pitrou commented
@ursabot crossbow run test-conda-cpp-valgrind

2020-01-31 12:22 UTC, pitrou commented
@ursabot crossbow submit test-conda-cpp-valgrind

2020-01-31 12:23 UTC, kszucs commented
[AMD64 Conda Crossbow Submit (#88852)](https://ci.ursalabs.org/#builders/98/builds/491) builder has been succeeded.

Revision: 43068985bf6a187ccc6ecf7ff3b6a035d9e93ad2

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-474](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-474)

|Task|Status|
|----|------|
|test-conda-cpp-valgrind|[![CircleCI](https://img.shields.io/circleci/build/github/ursa-labs/crossbow/ursabot-474-circle-test-conda-cpp-valgrind.svg)](https://circleci.com/gh/ursa-labs/crossbow/tree/ursabot-474-circle-test-conda-cpp-valgrind)|

2020-01-31 13:40 UTC, pitrou commented
I've enabled some optimizations, which makes the build faster locally:
```
$ docker-compose run --rm conda-cpp-valgrind

[ ... ]

100% tests passed, 0 tests failed out of 78

Label Time Summary:
arrow-tests      = 325.75 sec*proc (60 tests)
arrow_dataset    =  44.34 sec*proc (8 tests)
parquet-tests    = 106.69 sec*proc (7 tests)
plasma-tests     =  43.06 sec*proc (3 tests)
unittest         = 519.84 sec*proc (78 tests)

```

2020-01-31 13:40 UTC, pitrou commented
@ursabot crossbow submit test-conda-cpp-valgrind

2020-01-31 13:40 UTC, kszucs commented
[AMD64 Conda Crossbow Submit (#88862)](https://ci.ursalabs.org/#builders/98/builds/492) builder has been succeeded.

Revision: 79d47a33bd1eb3d96cdbc23c4f7b2236bfef7ded

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-475](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-475)

|Task|Status|
|----|------|
|test-conda-cpp-valgrind|[![CircleCI](https://img.shields.io/circleci/build/github/ursa-labs/crossbow/ursabot-475-circle-test-conda-cpp-valgrind.svg)](https://circleci.com/gh/ursa-labs/crossbow/tree/ursabot-475-circle-test-conda-cpp-valgrind)|

2020-02-03 16:18 UTC, kszucs commented on docker-compose.yml
> +    #   docker-compose run --rm conda-cpp
`docker-compose run --rm conda-cpp-valgrind`

2020-02-03 16:21 UTC, kszucs commented on ci/scripts/cpp_build.sh
> +      -DBUILD_WARNING_LEVEL=${BUILD_WARNING_LEVEL:-CHECKIN} \
Hard to spot!

2020-02-03 16:22 UTC, kszucs commented
@ursabot crossbow --help

2020-02-03 16:23 UTC, kszucs commented
@ursabot crossbow submit --help

2020-02-03 16:24 UTC, kszucs requested changes
Just a nit in the docker-compose comment.

2020-02-05 09:42 UTC, pitrou commented
@kszucs Anything else? macOS failure is unrelated.

2020-02-10 13:21 UTC, kszucs approved these changes
LGTM

2020-02-10 13:52 UTC, closed without merging