ARROW-7625: [Parquet][GLib] Add support for writer properties
apache/arrow pull request #6336
Opened 2020-02-01 16:24 UTC by shiro615

2020-02-02 21:47 UTC, kou requested changes
`parquet::WriterProperties::Builder` API is useful for C++ because we can use method chain to build properties:

```c++
builder
  .memory_pool(pool)
  .enable_dictionary()
  .data_pagesize(1024);
```

But this API isn't useful in C because we can't use method chain in C:

```c
gparquet_writer_properties_data_pagesize(
  gparquet_writer_properties_enable_dictionary(
    gparquet_writer_properties_memory_pool(builder, pool)
  ),
  1024);
```

Or

```c
gparquet_writer_properties_builder_memory_pool(builder, pool);
gparquet_writer_properties_builder_enable_dictionary(builder);
gparquet_writer_properties_builder_data_pagesize(builder, 1024);
```

So we don't need to provide the builder API to users.

We can just use `parquet::WriterProperties::Builder` internally. We can provide just accessor API:

```c
gparquet_writer_properties_set_memory_pool(properties, pool);
gparquet_writer_properties_enable_dictionary(properties);
gparquet_writer_properties_set_data_pagesize(properties, 1024);
```

And we can build `parquet::WriterProperties` when it's needed:

```c
gparquet_arrow_file_writer_new_*()
{
  ...
  auto parquet_writer_properties =
    gparquet_writer_properties_get_raw(writer_properties);
  ...
}
```

Could you change the API or do I push base implementation?

2020-02-02 21:49 UTC, kou commented
Could you enable Parquet on macOS CI?

```diff
diff --git a/.github/workflows/ruby.yml b/.github/workflows/ruby.yml
index bc28c6f54..f9ba56b67 100644
--- a/.github/workflows/ruby.yml
+++ b/.github/workflows/ruby.yml
@@ -85,6 +85,7 @@ jobs:
       ARROW_HOME: /usr/local
       ARROW_JEMALLOC: OFF
       ARROW_ORC: OFF
+      ARROW_PARQUET: ON
       ARROW_WITH_BROTLI: ON
       ARROW_WITH_LZ4: ON
       ARROW_WITH_SNAPPY: ON
```

2020-02-04 15:33 UTC, shiro615 commented
Thank you for your review.
I'll try to address them.

2020-02-05 16:47 UTC, shiro615 commented
@kou 
https://github.com/apache/arrow/pull/6336/commits/fbe3f6625f5cc277194ef8ff534e973e451c7ff4
Could you please confirm my understanding?
I'll add the other properties in this PR if this change is fine.

2020-02-06 03:55 UTC, kou reviewed
Could you check my comments?

2020-02-06 03:55 UTC, kou commented on c_glib/parquet-glib/arrow-file-writer.cpp
> +{
We can always create `parquet::WriterPropertiesBuilder` here.
We don't need to receive it as an argument of `g_object_new()`.

2020-02-06 03:55 UTC, kou commented on c_glib/parquet-glib/arrow-file-writer.cpp
> +  return priv->builder->build();
I want to cache `build()` result.

```cpp
if (priv->changed) {
  priv->properties = priv->builder->build(); 
}
return priv->properties;
```

2020-02-06 03:55 UTC, kou commented on c_glib/parquet-glib/arrow-file-writer.cpp
> +  return priv->compression_type;
I don't want to keep duplicated information in this object.

```cpp
auto parquet_properties = gparquet_writer_properties_get_raw(properties);
auto parquet_column_path = parquet::Schema::ColumnPath::FromDotString(dotstring); // Or receive as an argument
auto arrow_compression = parquet_properties->compression(parquet_column_path);
return garrow_compression_type_from_raw(arrow_compression);
```

2020-02-06 15:42 UTC, shiro615 commented
Thank you for your comments.
I'll fix them in this week.

2020-02-06 20:59 UTC, ziggythehamster commented
Nice catch with the other configurables (dictionary, memory pool) and exposing the per-column settings. I was happy with:

```c
parquet::WriterProperties::Builder builder;
builder.compression(arrow::Compression::SNAPPY);
auto parquet_writer_properties = builder.build();
```

:P

2020-02-07 00:44 UTC, kou commented
@ziggythehamster What do you mean? Do you want to use `parquet::WriterProperties` built by C++ with Apache Arrow GLib?

2020-02-08 00:44 UTC, shiro615 commented
I hope I've addressed all comments. In addition to them, I've added some properties.

2020-02-09 21:31 UTC, kou requested changes
Could you check my comments?

2020-02-09 21:31 UTC, kou commented on c_glib/parquet-glib/arrow-file-writer.cpp
> + * gparquet_writer_properties_get_compression:
Could you append `_dot_string`?
Because we will add `parquet::Schema::ColumnPath` version later.

2020-02-09 21:31 UTC, kou commented on c_glib/parquet-glib/arrow-file-writer.cpp
> + * @dotstring: The dot string path.
`@dot_string`

2020-02-09 21:31 UTC, kou commented on c_glib/parquet-glib/arrow-file-writer.cpp
> + *
`@dot_string` is missing.

2020-02-09 21:31 UTC, kou commented on c_glib/parquet-glib/arrow-file-writer.cpp
> + * gparquet_writer_properties_dictionary_enabled:
Could you add `is_` for predicate?
`gparquet_writer_properties_is_dictionary_enabled`.

2020-02-09 21:31 UTC, kou commented on c_glib/parquet-glib/arrow-file-writer.cpp
> + * @dictionary_pagesize_limit: The dictionary page size limit.
We can simplify this to `@limit`.

2020-02-09 21:31 UTC, kou commented on c_glib/parquet-glib/arrow-file-writer.cpp
> + * @max_row_group_length: The max row group length.
We can simplify this to `@length`.

2020-02-09 21:31 UTC, kou commented on c_glib/parquet-glib/arrow-file-writer.cpp
> + * @data_pagesize: The data page size.
Should we use `page_size` instead of `pagesize`?

2020-02-09 21:31 UTC, kou commented on c_glib/parquet-glib/arrow-file-writer.cpp
> +                                     GParquetWriterProperties *writer_properties,
This breaks API backward compatibility but it may be acceptable...

2020-02-09 21:31 UTC, kou commented on c_glib/parquet-glib/arrow-file-writer.cpp
> +  priv->changed = FALSE;
Could you put this to `if (priv->changed) {` clause?

2020-02-09 21:31 UTC, kou commented on c_glib/test/parquet/test-writer-properties.rb
> +                 @properties.get_compression("a_column"))
Could you use `not-specified` or something instead of `a_column`?

2020-02-09 21:31 UTC, kou commented on c_glib/parquet-glib/arrow-file-writer.cpp
> +                                           GArrowCompressionType compression_type)
How about adding nullable `path` or `dot_string`?

```cpp
gparquet_writer_properties_set_compression((GParquetWriterProperties *properties,
                                           const gchar *path,
                                           GArrowCompressionType compression_type)
```

2020-02-11 14:54 UTC, shiro615 commented on c_glib/parquet-glib/arrow-file-writer.cpp
> +                                           GArrowCompressionType compression_type)
I've added nullable `path`.

2020-02-15 18:13 UTC, shiro615 commented
Thank you for your review. I think I've addressed them.

2020-02-26 21:57 UTC, kou approved these changes
+1

@shiro615 Sorry for my late review.
I pushed some changes:

* Add the "path" argument to `enable_dictionary()` and `disable_dictionary()`.
* Rename the "dot_string" argument to "path".  Sorry. How about using "path" as "dot string" in Parquet GLib? We will use "column_path" when we need to export `Parquet::Schema::ColumnPath`.

Could you confirm them?

2020-02-27 04:33 UTC, shiro615 commented
Thank you for your review and suggestion.
> How about using "path" as "dot string" in Parquet GLib?

It sounds good for me too.

I'll merge this.

2020-02-27 04:35 UTC, closed without merging