Add date/time/duration/timestamp types to filter kernel
apache/arrow pull request #6455
Opened 2020-02-19 16:40 UTC by maxburke

The filter kernel was missing implementations for the temporal types (ie: date / time / duration / timestamp).

2020-02-19 17:13 UTC, andygrove reviewed
LGTM but could you add some tests?

2020-02-19 17:51 UTC, maxburke commented
@andygrove Done!

2020-02-20 06:00 UTC, nevi-me requested changes
Thanks for adding the filters, please see my comment on adding the `def_numeric_from_vec! {}` for timestamp arrays

2020-02-21 05:29 UTC, nevi-me approved these changes

2020-02-21 06:25 UTC, closed without merging