ARROW-8131: Add dynamic attributes to PyArrow ExtensionArray
apache/arrow pull request #6630
Opened 2020-03-16 10:15 UTC by balancap

2020-03-16 14:48 UTC, kszucs commented on python/pyarrow/array.pxi
> +    cdef dict __dict__
@balancap please add this to lib.pxd

2020-03-16 14:50 UTC, kszucs commented
I'm not sure that we should support dynamic attributes, but please add tests cases which could reason about it.

cc @jorisvandenbossche

2020-03-16 14:51 UTC, kszucs requested changes
I'm not sure that we should support dynamic attributes, but please add tests cases which could reason about it.

2020-03-24 17:26 UTC, kszucs commented
@balancap can we close this in favor of #6653?

2020-03-24 19:05 UTC, balancap commented
Indeed. Closed the Jira ticket as well.

2020-03-24 19:05 UTC, closed without merging