ARROW-8409: [R] Add R wrappers for getting and setting global CPU thread pool capacity
apache/arrow pull request #6906
Opened 2020-04-12 21:23 UTC by wesm

I needed this while running some benchmarks.

2020-04-12 21:24 UTC, wesm commented on r/man/enums.Rd
> -}
@nealrichardson do you know what this is about?

2020-04-13 03:05 UTC, nealrichardson requested changes
Seems ok, just a few suggestions on the details.

2020-04-13 03:05 UTC, nealrichardson commented on r/R/config.R
> +#' @export
If you want these functions to appear on the doc website table of contents, add `cpu_count` to the list in `r/_pkgdown.yml`, probably somewhere around L130. If you don't want to publicize these functions, add a line with `#' @keywords internal` around here (the man pages will still show up on the website, just not included on the ToC). Either way is fine with me.

2020-04-13 18:32 UTC, wesm commented on r/man/enums.Rd
> -}
That did it

2020-04-13 18:34 UTC, wesm commented on r/R/config.R
> +cpu_count <- function() {
Indeed, they are just the raw Rcpp functions. I had written tests for these but apparently forgot to check it in. Adapted

2020-04-13 19:17 UTC, nealrichardson commented on r/R/config.R
> +#'
```suggestion
```

2020-04-13 19:17 UTC, nealrichardson commented on r/_pkgdown.yml
> +  - set_cpu_count
```suggestion
```

They're documented in the same file so you only include them once.

2020-04-13 19:18 UTC, nealrichardson approved these changes
LGTM, thanks @wesm

2020-04-13 20:36 UTC, closed without merging