ARROW-9345: [C++][Dataset] Support casting scalars to dictionary scalars
apache/arrow pull request #7686
Opened 2020-07-08 18:52 UTC by bkietz

2020-07-08 20:03 UTC, jorisvandenbossche reviewed
For the C++ changes: you basically enabled casting to DictionaryScalar? (so that implicit casts in the dataset filter expression works?)

The enabled behaviour certainly looks good!

2020-07-08 20:05 UTC, bkietz commented
@jorisvandenbossche precisely

2020-07-09 12:36 UTC, pitrou requested changes
LGTM, but can you add tests on the C++ side?

2020-07-09 20:44 UTC, bkietz commented
@pitrou done, PTAL

2020-07-10 08:22 UTC, pitrou commented on cpp/src/arrow/scalar_test.cc
> -  auto CheckIndexType = [&](const std::shared_ptr<DataType>& index_ty) {
Ha, this function was never called?

2020-07-10 08:25 UTC, pitrou commented on cpp/src/arrow/scalar_test.cc
> +        ArrayFromJSON(utf8(), R"(["alpha", "beta", "gamma"])"));
Hmm, perhaps test for null as well?

2020-07-10 08:25 UTC, pitrou approved these changes
I don't know if you'd like to quickly add a test for null, otherwise please merge :-)

2020-07-10 12:19 UTC, bkietz commented
The null case doesn't hit the new code here, so I think I'll merge now and add more tests in follow up

2020-07-10 12:25 UTC, closed without merging