ARROW-9463:[Go] The writer is double closed in TestReadWrite
apache/arrow pull request #7754
Opened 2020-07-14 13:03 UTC by fredgan

2020-07-17 01:32 UTC, fredgan commented
@sbinet Hi, would you mind having a look?

2020-07-17 07:28 UTC, sbinet requested changes
I think the correct fix would be to make Writer.Close idempotent so the usual idiom of a 'defer w.Close()' can be used.

2020-07-17 08:11 UTC, fredgan commented
Yes, you are right. It's better than just deleting the redundant Close().

2020-08-04 13:03 UTC, sbinet approved these changes

2020-08-04 13:06 UTC, closed without merging