ARROW-9402: [C++] Rework portable wrappers for checked integer arithmetic
apache/arrow pull request #7784
Opened 2020-07-16 11:49 UTC by pitrou

Vendor relevant code from the portable-snippets library (~ public domain):
https://github.com/nemequ/portable-snippets/tree/master/safe-math

Also fix some bugs in checked arithmetic (null values had their value slots checked as well),
add compute scaffolding for stateful binary scalar functions.

2020-07-16 15:55 UTC, pitrou commented
I think I finally squashed the horrid Windows preprocessor macro issues (Windows headers define OPTIONAL, but you can't undef it blindly because other subsequent includes may require it...).
AppVeyor build: https://ci.appveyor.com/project/pitrou/arrow/builds/34135787

2020-07-16 15:56 UTC, pitrou commented
@wesm You'll probably want to take a look at the codegen changes when you have some time.

2020-08-05 17:21 UTC, pitrou commented
Rebased. @wesm could you perhaps review this?

2020-08-05 17:21 UTC, pitrou commented
Or perhaps @bkietz .

2020-08-06 15:04 UTC, bkietz requested changes
Some minor comments, this mostly looks good to me

2020-08-10 12:26 UTC, pitrou commented on cpp/src/arrow/compute/kernels/scalar_arithmetic.cc
> +    static_assert(std::is_same<T, Arg0>::value && std::is_same<T, Arg1>::value, "");
It doesn't compile, because `Call` is invoked with explicit template arguments by the kernel execution machinery.

2020-08-10 12:30 UTC, pitrou commented on cpp/src/arrow/compute/kernels/test_util.cc
> +  std::vector<std::shared_ptr<Array>> sliced;
Good idea, thank you.

2020-08-10 12:32 UTC, pitrou commented on cpp/src/arrow/compute/kernels/scalar_arithmetic_test.cc
> +                ArrayFromJSON(type_singleton(), rhs), expected);
Indeed :-)

2020-08-10 13:33 UTC, pitrou commented
I believe I addressed your comments @bkietz , so I'm going to merge now.

2020-08-10 13:33 UTC, closed without merging