ARROW-5394: [C++][Benchmark] IsIn and IndexIn benchmark for integer and string types
apache/arrow pull request #8529
Opened 2020-10-26 16:22 UTC by david1437

2020-10-26 18:30 UTC, david1437 commented
CI errors seem unrelated

2020-11-09 15:29 UTC, pitrou requested changes
Thank you for doing this. Here are some comments.

Also, can you rebase on git `master`?

2020-11-09 15:29 UTC, pitrou commented on cpp/src/arrow/compute/kernels/scalar_set_lookup_benchmark.cc
> +                                     const int32_t valueSetLength) {
Should be `value_set_length`.

2020-11-09 15:29 UTC, pitrou commented on cpp/src/arrow/compute/kernels/scalar_set_lookup_benchmark.cc
> +  ABORT_NOT_OK(CallFunction(func_name, {values, value_set}));
Is the first call for warmup?

2020-11-09 15:29 UTC, pitrou commented on cpp/src/arrow/compute/kernels/scalar_set_lookup_benchmark.cc
> +                          (state.iterations() * valueSetLength));
It doesn't seem logical to add this second term. The "items" processed are the input array items.

2020-11-09 15:29 UTC, pitrou commented on cpp/src/arrow/compute/kernels/scalar_set_lookup_benchmark.cc
> +                          (state.iterations() * value_set->data()->buffers[2]->size()));
Ditto here.

2020-11-09 15:29 UTC, pitrou commented on cpp/src/arrow/compute/kernels/scalar_set_lookup_benchmark.cc
> +static void IndexInStringSmall(benchmark::State& state) {
Call this "SmallSet" instead of "Small"?

2020-11-09 15:29 UTC, pitrou commented on cpp/src/arrow/compute/kernels/scalar_set_lookup_benchmark.cc
> +static void IndexInStringLarge(benchmark::State& state) {
"LargeSet"?

2020-11-09 15:29 UTC, pitrou commented on cpp/src/arrow/compute/kernels/scalar_set_lookup_benchmark.cc
> +  SetLookupBenchmarkString(state, "index_in_meta_binary", 1 << 20);
`1 << 20` sounds very large and irrealistic for a lookup set. How about `1 << 10` (which is already quite a lot of lookup strings).

2020-11-09 15:29 UTC, pitrou commented on cpp/src/arrow/compute/kernels/scalar_set_lookup_benchmark.cc
> +  const int64_t value_max_size = 32;
Well, for more realistic data, how about using `std::numeric_limits<Type::c_type>::max()` instead?

2020-11-09 15:29 UTC, pitrou commented on cpp/src/arrow/compute/kernels/scalar_set_lookup_benchmark.cc
> +BENCHMARK(IndexInStringSmall)->RangeMultiplier(2)->Range(2, 64);
We may cut down on the number of benchmark instances and use `RangeMultiplier(4)` instead.

2020-11-09 17:48 UTC, david1437 commented on cpp/src/arrow/compute/kernels/scalar_set_lookup_benchmark.cc
> +  ABORT_NOT_OK(CallFunction(func_name, {values, value_set}));
Yes exactly

2020-11-09 17:49 UTC, david1437 commented
Not too proficient with git so hopefully, I rebased correctly.  Added changes as you recommended.

2020-11-09 19:10 UTC, pitrou commented
Ok, it seems the git situation is still a bit messed up, I'll fix it up :-)

2020-11-09 19:19 UTC, pitrou approved these changes
Thank you @david1437 . I'll merge if CI is green.

2020-11-09 21:28 UTC, closed without merging