ARROW-1237: expose the ability to set lastSet
apache/arrow pull request #868
Opened 2017-07-19 19:52 UTC by siddharthteotia

The changes here expose the ability to set "lastSet" on Nullable<var length>Vector. 
I believe this is needed only for NullableVarCharVector and NullableVarBinaryVector. Hence the API is exposed through NullableValueVectors.java

2017-07-19 23:06 UTC, wesm commented
Is it possible to add a unit test for this? Can you also indicate in the PR title that this is a Java patch, e.g. `[Java]` or `[JAVA]`?

2017-07-19 23:14 UTC, siddharthteotia commented
Edited the PR title to include [JAVA].
Let me get back after giving a thought on unit-tests

2017-07-20 16:33 UTC, DremioQA requested changes
Let's add some unit tests for each version that has last set. Basically, set some data via memory access then update last set, then confirm a correct vector output.

2017-07-20 16:33 UTC, DremioQA commented on java/vector/src/main/codegen/templates/NullableValueVectors.java
> +      <#if type.major = "VarLen">lastSet = value;</#if>
Is there a lastset for the list vector as well?

2017-07-20 16:42 UTC, siddharthteotia commented on java/vector/src/main/codegen/templates/NullableValueVectors.java
> +      <#if type.major = "VarLen">lastSet = value;</#if>
Writing the unit tests. 

Yes, the ListVector also has lastSet. Will add the API for ListVector as well and unit tests for each vector type; NullableVarCharVector, NullableVarBinaryVector, ListVector.

2017-07-20 17:31 UTC, siddharthteotia commented on java/vector/src/main/codegen/templates/NullableValueVectors.java
> +      <#if type.major = "VarLen">lastSet = value;</#if>
@DremioQA

2017-07-22 00:14 UTC, siddharthteotia commented
@jacques-n 
I have added some unit tests to ensure correctness of vector data with the usage of setLastSet(). 

There is a slightly orthogonal test case test based on VectorLoader and VectorUnloader. 
If it looks redundant, I will remove it. It was written since my initial understanding on loading a vector was based on VectorLoader and VectorUnloader. Probably no harm to leave it since it still tests the loading-unloading of Nullable<var length> vector.

2017-07-22 16:44 UTC, jacques-n commented on java/vector/src/test/java/org/apache/arrow/vector/TestValueVector.java
> +      assertArrayEquals(STR3, accessor1.get(2));
Given the main issue of holes/blanks in the items set, I suggest you modify these tests to set the valuecount to something higher (e.g. 15). Then verify that everything looks good.

2017-07-24 10:37 UTC, siddharthteotia commented on java/vector/src/test/java/org/apache/arrow/vector/TestValueVector.java
> +      assertArrayEquals(STR3, accessor1.get(2));
Added additional test and slightly modified existing ones.

2017-07-24 15:15 UTC, closed without merging