ARROW-10881: [C++] Fix EXC_BAD_ACCESS in PutSpaced
apache/arrow pull request #9097
Opened 2021-01-04 21:13 UTC by xhochy

2021-01-04 22:10 UTC, emkornfield commented
Is it possible to add a unit test?

2021-01-04 22:16 UTC, xhochy commented
@github-actions autotune

2021-01-04 23:59 UTC, nealrichardson commented
@xhochy autotune isn't working at the moment--INFRA has blocked some of the Actions we use, including on that workflow. See https://issues.apache.org/jira/browse/INFRA-21239

2021-01-05 11:30 UTC, pitrou requested changes
It would indeed be nice if there was a test.

2021-01-05 11:30 UTC, pitrou commented on cpp/src/parquet/encoding.cc
> +      T* data_ = reinterpret_cast<T*>(buffer->mutable_data());
Underscore-terminated variable names are only for attributes. Can you use another name? (e.g. `non_spaced_data`)

2021-01-05 11:30 UTC, pitrou commented on cpp/src/parquet/encoding.cc
> +                                                                   this->memory_pool()));
It seems `buffer` will be deallocated at the end of this `if` block, but you're using its contents afterwards (when calling `Put`).

2021-01-05 11:30 UTC, pitrou commented on cpp/src/parquet/encoding.cc
> +      PARQUET_ASSIGN_OR_THROW(auto buffer, ::arrow::AllocateBuffer(num_values * sizeof(T),
Same concerns below.

2021-01-05 11:30 UTC, pitrou commented on cpp/src/parquet/encoding.h
> +      return num_values;
Why don't you call `Decode` in this branch?

2021-01-05 17:58 UTC, pitrou approved these changes

2021-01-05 18:49 UTC, pitrou commented
CI tests are green on my fork (except for the usual Homebrew dependency install failures).

2021-01-05 18:50 UTC, closed without merging

2021-01-05 20:13 UTC, xhochy commented
@pitrou Thanks!