ARROW-11601: [C++][Python][Dataset] expose Parquet pre-buffer option
apache/arrow pull request #9482
Opened 2021-02-12 16:33 UTC by lidavidm

This exposes the pre-buffering option that was implemented for the base Parquet reader in Datasets.

To summarize, the option coalesces and buffers ranges of a file based on the columns and row groups read, issuing a single read operation for multiple read requests, by combining adjacent and "nearby" ranges into a single request. This means it handles both cases where the entire file is being read, as well as a subset of columns and/or row groups.

There's not a benchmark for Datasets in the repo, but here's a quick comparison for loading data from S3:

```
Without buffering:
Data read: 1300.00 MiB
Mean     : 7.68 s
Median   : 7.48 s
Stdev    : 0.76 s
Mean rate: 170.57 MiB/s

With buffering:
Data read: 1300.00 MiB
Mean     : 3.88 s
Median   : 3.89 s
Stdev    : 0.21 s
Mean rate: 335.95 MiB/s
```

The code being benchmarked is essentially:

```python
dataset = pyarrow.dataset.FileSystemDataset.from_paths(
    paths,
    schema=schema,
    format=format,
    filesystem=fs,
)
table = dataset.to_table()
```

2021-02-17 17:10 UTC, bkietz requested changes
This looks good but I'd like to see at least one python test which exercises this option when reading a dataset. Could be added as a parameter of `test_filesystem_factory`:

```diff
--- a/python/pyarrow/tests/test_dataset.py
+++ b/python/pyarrow/tests/test_dataset.py
@@ -521,9 +521,11 @@ def test_file_format_pickling():
         'subdir/2/yyy/file1.parquet',
     ]
 ])
-def test_filesystem_factory(mockfs, paths_or_selector):
+@pytest.mark.parametrize('pre_buffer', [False, True])
+def test_filesystem_factory(mockfs, paths_or_selector, pre_buffer):
     format = ds.ParquetFileFormat(
-        read_options=ds.ParquetReadOptions(dictionary_columns={"str"})
+        read_options=ds.ParquetReadOptions(dictionary_columns={"str"},
+                                           pre_buffer=pre_buffer)
     )

     options = ds.FileSystemFactoryOptions('subdir')
```

2021-02-17 18:32 UTC, bkietz approved these changes
LGTM, thanks!

CI failure is unrelated, will merge

2021-02-17 20:33 UTC, dianaclarke commented
@ursabot please benchmark

2021-02-18 15:02 UTC, lidavidm commented
We found a segfault in an external benchmark, so let's hold off on merging for now.

2021-02-18 15:49 UTC, lidavidm commented
The issue is that the buffer is shared at the Parquet FileReader level, so if we enable the pre-buffer option at the Arrow RowGroupReader level, executing scan tasks may trample that buffer (each will try to buffer a different row group). We don't notice it in unit tests since pre-buffering is trivial. 

One solution would be to manually pre-buffer once at the 'top level', when we create scan tasks. That has some advantages: all the scan tasks would share the same buffer, so there's more opportunities for I/O savings. (If you read the last column of row group 0 and the first column of row group 1, then you'd be able to coalesce those into a single I/O operation.) But that means generating the scan tasks would trigger work that happens right away, which is undesirable. 

We could give each scan task its own copy of the Parquet reader. This would be OK, but we'll need some refactoring so that we don't re-open and re-read the Parquet footer for each scan task. We also won't get those potential I/O coalescing opportunities.

We could generate a synthetic scan task that starts the pre-buffering. I think that isn't safe, though, for users who execute scan tasks in parallel.

We could hand each scan task a shared_ptr<once_flag> that handles the pre-buffering (if present); each scan task would then call that once_flag before continuing. I think I like this the best.

@bkietz What do you think?

2021-02-18 16:15 UTC, lidavidm commented
I've pushed that last option so you can take a look.

2021-02-18 16:15 UTC, bkietz commented
The `once_flag` approach sounds viable in principle. However I'm concerned that it could cause lots of threads to block for a single pre-buffering, then block them all pre-buffering for the next file, etc. For example, a parquet fragment with 42 row groups will generate a scan task for each, and if one of those tasks is scheduled first in each thread (as in Scanner::ToTable) then I think they'd block the whole pool.

Fundamentally, it's part of the contract of ScanTask that two ScanTasks are independent, and any shared pre-buffering violates that. I think the correct fix for right now is to write another subclass of `ScanTask` which wraps a whole pre-buffered file reader rather than individual row groups. This will earn us most of the perf advantage of pre-buffering in the common case of scanning many files at the cost of losing parallelism when scanning few files.

Eventually we'll use `Future`s to resolve this, probably by replacing
```diff
-  virtual Result<RecordBatchIterator> Execute() = 0;
+  virtual AsyncGenerator<std::shared_ptr<RecordBatch>> Execute() = 0;
```
this will enable more fluid handling of the wait-for-pre-buffer: the first record batch from scan tasks which happen to originate from the same file will simply wait a bit longer

2021-02-18 16:17 UTC, lidavidm commented
Ah - to be clear, calling PreBuffer doesn't actually block until the data is read! It computes the coalesced read ranges, then asynchronously submits read requests for each of those ranges. The blocking happens later on, when the Parquet reader reads a chunk of the file.

2021-02-18 16:18 UTC, lidavidm commented
But the alternate ScanTask approach makes sense to me. Let me implement that.

2021-02-18 16:29 UTC, bkietz commented
If the blocking situation I described wouldn't happen, then pre buffering at top level is definitely preferable; we don't want to lose row group level parallelism if it's not necessary

2021-02-18 17:09 UTC, bkietz approved these changes
After closer inspection of `PreBuffer`, I no longer think the catastrophic blocking I described is a danger. This looks good to me modulo a minor style nit

2021-02-18 18:09 UTC, bkietz requested changes

2021-02-18 18:09 UTC, bkietz commented on cpp/src/arrow/dataset/file_parquet.cc
> +        pre_buffer_row_groups_(std::move(pre_buffer_row_groups_)),
Critical typo :D :
```suggestion
        pre_buffer_row_groups_(std::move(pre_buffer_row_groups)),
```

2021-02-18 18:09 UTC, bkietz commented on cpp/src/arrow/dataset/file_parquet.cc
> +  // case. We assume all scan tasks have the same column projection.
Not really a problem, butyou still set row_groups even if when not pre-buffering

2021-02-18 18:17 UTC, lidavidm commented on cpp/src/arrow/dataset/file_parquet.cc
> +        pre_buffer_row_groups_(std::move(pre_buffer_row_groups_)),
Third time's the charm, let's hope…

2021-02-18 19:36 UTC, westonpace commented
So `PreBuffer` needs to be called once and only once on a reader?  It seems this could be simplified if `PreBuffer` didn't immediately start reading (and waited for the first request) although I suppose that may only push the flag further down.

2021-02-18 19:48 UTC, lidavidm commented
> So `PreBuffer` needs to be called once and only once on a reader? It seems this could be simplified if `PreBuffer` didn't immediately start reading (and waited for the first request) although I suppose that may only push the flag further down.

It can be called multiple times, but all readers created from the file prior to the next call must be discarded first.

Also, you may want PreBuffer to start work immediately: you could pipeline decoding and I/O that way (start prebuffering immediately, then create and sequentially decode the row groups).

2021-02-18 19:48 UTC, lidavidm commented
I agree the API is a bit complex, but it was intentionally rather low-level while we worked out the uses for it.

2021-02-18 20:52 UTC, westonpace commented
Ok, I think I get it now.  Let's pretend we are outside of S3, there is 1 file, 3 row groups, and 3 columns.  Three scan tasks will be generated.  Task 1 needs RG1C1, RG1C2, RG1C3.  Task 2 needs RG2C1, RG2C2, RG2C3.  Task 3 needs RG3C1, RG3C2, RG3C3.

Prebuffer will be called asking for all 9 blocks and it will then issue three reads in parallel (instead of the 9 reads that would otherwise be issued) RG1, RG2, and RG3.

If there are only 3 columns in the file, is it possible Prebuffer would coalesce this all into one read?  In that case wouldn't all three tasks be blocked until the entire file is read, preventing the ability for task 1 to start running as soon as RG1 is issued?

2021-02-18 21:08 UTC, lidavidm commented
> Ok, I think I get it now. Let's pretend ~we are outside of S3,~ (nvm, S3 not relevant) there is 1 file, 3 row groups, and 3 columns. Three scan tasks will be generated. Task 1 needs RG1C1, RG1C2, RG1C3. Task 2 needs RG2C1, RG2C2, RG2C3. Task 3 needs RG3C1, RG3C2, RG3C3.
> 
> Prebuffer will be called asking for all 9 blocks and it will then issue three reads in parallel (instead of the 9 reads that would otherwise be issued) RG1, RG2, and RG3.

The number of reads that actually gets issued depends on the parameters but it would be anywhere from 1 to 9. (If you had a filesystem with high bandwidth but a very large time-to-first-byte, you'd issue one; if you had a filesystem with very low latency and high bandwidth, you'd issue all 9.)

> If there are only 3 columns in the file, is it possible Prebuffer would coalesce this all into one read? In that case wouldn't all three tasks be blocked until the entire file is read, preventing the ability for task 1 to start running as soon as RG1 is issued?

Yes, it's possible they'd all be coalesced into one read. You're trading off throughput for latency. The point is that for some filesystems, this can be faster than issuing separate reads. Picking numbers out of thin air, if it takes 10ms to establish a connection and 5ms to read one column, it's better making one request at (10ms + 3 * 5ms) than three requests at (10ms + 15ms) each (15ms since you're splitting the available bandwidth 3 ways).

I guess one thing I should mention is that just because two ranges are adjacent, doesn't mean that PreBuffer will always coalesce them (and furthermore, just because two ranges are adjacent, doesn't mean that PreBuffer won't coalesce them anyways and pay the penalty to read the extra data between them). 

Another is that the Parquet reader decodes one column at a time, and each column decoder will block until its chunk is read. So you're moving the blocking up front and hopefully consolidating it, instead of sequentially blocking several times.

2021-02-18 21:54 UTC, lidavidm commented
I re-ran my benchmark from above on the NYC Taxi dataset and the latest version of the code, while we're waiting for Ursabot. The optimization here is worth an order of magnitude, and that's without tuning the pre-buffering settings to S3 itself. (Note that I'm running from within EC2, which would skew it significantly compared to what Ursabot eventually reports.)

```
# pre_buffer=true
Data read: 4419.18 MiB
Mean     : 9.65 s
Median   : 9.49 s
Stdev    : 0.45 s
Mean rate: 458.70 MiB/s
```

I interrupted the pre_buffer=False run on accident before it finished, but:
```
Duration: 113.71 s
Rate:     38.86 MiB/s
Duration: 111.82 s
Rate:     39.52 MiB/s
Duration: 109.96 s
Rate:     40.19 MiB/s
Duration: 108.82 s
Rate:     40.61 MiB/s
Duration: 111.06 s
Rate:     39.79 MiB/s
Duration: 111.14 s
Rate:     39.76 MiB/s
Duration: 111.66 s
Rate:     39.58 MiB/s
Duration: 113.84 s
Rate:     38.82 MiB/s
Duration: 111.17 s
Rate:     39.75 MiB/s
```

2021-02-18 22:30 UTC, dianaclarke commented
Some conbench results are now reporting (Note: not run in EC2).

<img width="1008" alt="dataset-read" src="https://user-images.githubusercontent.com/878798/108429699-924b3900-71fd-11eb-9d17-cfa9857fdac8.png">

Note that the percent changed is zero because master doesn't yet have the pre-buffer read option, so the baseline case is `None`, and the contender cases are `True` & `False`, and it doesn't try to compare apples to oranges. I should probably change the percent changed to `---` in this case. I'll fix that up shortly.

Baseline (no read options):
https://conbench.ursa.dev/benchmarks/f229c4463cdb4dc99f572ab3bde2b013/
3 iterations (unit seconds): `['72.086552', '59.959338', '43.372681']`

Contender (pre_buffer=False):
https://conbench.ursa.dev/benchmarks/57e4936660104ce587e5f4721124810c/
3 iterations (unit seconds): `['43.061806', '43.123252', '41.576502']`

Contender (pre_buffer=True)
https://conbench.ursa.dev/benchmarks/654b3867cb1e443eb5f7c73ce304aca1/
3 iterations (unit seconds): `['37.517980', '32.662669', '34.644381']`

2021-02-18 22:34 UTC, lidavidm commented
Thanks! It does seem a little better, but isn't drastic in this case. It would help if we tuned the pre-buffer settings for the characteristics of S3 as seen from the non-EC2 machine but that's not really worth doing. (Unless people reading from S3 over the broader Internet is a thing? It'd also be interesting to see how cross-region reads behave in EC2 itself. These are all future questions of course.)

2021-02-19 15:51 UTC, bkietz approved these changes
LGTM, will merge

2021-02-19 15:51 UTC, closed without merging