ARROW-11872 [C++]: Fix Array validation when Array contains non-CPU buffers
apache/arrow pull request #9640
Opened 2021-03-05 20:30 UTC by trxcllnt

Constructing an Arrow Table from Arrays that contains `CudaBuffer` presently fails.

`ValidateArrayImpl::IsBufferValid` is checking the buffers of each Array, but when an Array's buffers aren't on the CPU the `data.buffers[index]->data() != nullptr` check returns false.

Fixes [ARROW-11872](https://issues.apache.org/jira/browse/ARROW-11872).

2021-03-07 17:57 UTC, kiszk commented
Looks good

2021-03-08 14:02 UTC, pitrou requested changes
Thanks for doing this. Can you add an array validation test on the C++ side? Also, see comments below.

2021-03-08 14:02 UTC, pitrou commented on cpp/src/arrow/array/validate.cc
> +                                          : true);
This is basically disabling the check on non-CPU buffers. Rather, you should use `data.buffers[index]->address()`.

2021-03-08 14:02 UTC, pitrou commented on python/pyarrow/tests/test_cuda.py
> +    ).read_all())
This isn't much different from the test above, can you refactor the common bits?

2021-03-08 19:39 UTC, pitrou commented
Thanks for the update @trxcllnt . As I said above, perhaps you can add an array validation test on the C++ side?

2021-03-08 21:51 UTC, trxcllnt commented
@pitrou yep, done!

2021-03-09 09:25 UTC, pitrou approved these changes
+1, thanks for the fix @trxcllnt

2021-03-09 11:34 UTC, closed without merging