ARROW-10606: [C++] WIP: implement Decimal256 casts
apache/arrow pull request #9751
Opened 2021-03-18 21:35 UTC by lidavidm

This likely needs more testing, especially where I had to implement functionality in (Basic)Decimal256. Also, we may want to extend the scalar cast benchmarks to cover decimals. There's also potentially some redundancy to eliminate in the tests.

2021-03-19 17:36 UTC, lidavidm commented on cpp/src/arrow/util/decimal.cc
> +    1e36f,    1e37f,    1e38f,    INFINITY, INFINITY, INFINITY, INFINITY, INFINITY,
Looks like INFINITY is actually a double on the Windows R toolchain.

2021-03-19 17:36 UTC, lidavidm commented on cpp/src/arrow/util/decimal_test.cc
> +    CheckDecimalFromRealIntegerString<Decimal128>(real, 1, -scale, "1");
Two things:
- This apparently fails on Windows MinGW32 due to precision issues.
- This didn't fail before - something changed. Possibly I do have to figure out how to use ASSERT_FLOAT_EQ/ASSERT_DOUBLE_EQ as appropriate.

2021-03-22 15:07 UTC, lidavidm commented
CC @bkietz and @emkornfield.

2021-03-23 14:33 UTC, pitrou requested changes
Thanks a lot for doing this. Here are some comments.

2021-03-23 14:33 UTC, pitrou commented on cpp/src/arrow/compute/kernels/scalar_cast_numeric.cc
> +      func->AddKernel(Type::DECIMAL128, {InputType(Type::DECIMAL256)}, sig_out_ty, exec));
Note the signature of `CastFunction::AddKernel`:
```c++
  Status AddKernel(Type::type in_type_id, std::vector<InputType> in_types,
                   OutputType out_type, ArrayKernelExec exec,
                   NullHandling::type = NullHandling::INTERSECTION,
                   MemAllocation::type = MemAllocation::PREALLOCATE);
```

2021-03-23 14:33 UTC, pitrou commented on cpp/src/arrow/util/basic_decimal.h
> +  ///   rounded up (+1 for +ve, -1 for -ve) based on the value of the dropped digits
Write "positive" and "negative" in full?

2021-03-23 14:33 UTC, pitrou commented on cpp/src/arrow/util/decimal.cc
> +static constexpr float kFloatInf = std::numeric_limits<float>::infinity();
Is this used? You're still using `INFINITY` below.

2021-03-23 14:33 UTC, pitrou commented on cpp/src/arrow/util/decimal.h
> +  /// \brief Convert to a floating-point number (scaled)
Mention that the result can be an infinite in case of overflow?

2021-03-23 14:33 UTC, pitrou commented on cpp/src/arrow/util/decimal_test.cc
> +    ::testing::Values(
Since those are the same values as for Decimal128, factor them out in a global variable?

2021-03-23 14:33 UTC, pitrou commented on cpp/src/arrow/util/decimal_test.cc
> +TEST(TestDecimal256FromRealFloat, LargeValues) {
Perhaps fold this test into `TestDecimalFromReal`, to avoid repeating it for both decimal types?

2021-03-23 14:33 UTC, pitrou commented on cpp/src/arrow/util/decimal_test.cc
> +                            "824207571575210.5414230016"}
This is the same test vector as above + 4 additional values. Perhaps factor out the common values?

2021-03-23 14:33 UTC, pitrou commented on cpp/src/arrow/util/decimal_test.cc
> +class TestDecimalToRealFloat : public TestDecimalToReal<std::pair<Decimal128, float>> {};
Rename to `TestDecimal128ToRealFloat`?

2021-03-23 14:33 UTC, pitrou commented on cpp/src/arrow/util/decimal_test.cc
Rename `TestDecimalFromRealDouble` to `TestDecimal128FromRealDouble`?

2021-03-23 14:33 UTC, pitrou commented on cpp/src/arrow/util/decimal_test.cc
> +class TestDecimalToRealDouble : public TestDecimalToReal<std::pair<Decimal128, double>> {
Rename to `TestDecimal128ToRealDouble`?

2021-03-23 14:33 UTC, pitrou commented on cpp/src/arrow/util/decimal_test.cc
> +TEST_F(TestDecimal256ToRealDouble, LargeValues) {
Instead of copy-pasting these test functions, why not factor them out?
(for example as `TestDecimalToReal` methods?)

2021-03-23 14:33 UTC, pitrou commented on cpp/src/arrow/compute/kernels/scalar_cast_test.cc
> +TEST(Cast, Decimal256ToInt) {
Nit, but rename `DecimalToInt` to `Decimal128ToInt` above?

2021-03-23 14:33 UTC, pitrou commented on cpp/src/arrow/compute/kernels/scalar_cast_test.cc
> +TEST(Cast, Decimal256ToDecimal256) {
Rename `DecimalToDecimal` to `Decimal128ToDecimal128`?

2021-03-23 14:33 UTC, pitrou commented on cpp/src/arrow/compute/kernels/scalar_cast_test.cc
> +TEST(Cast, DecimalToDecimal256) {
`Decimal128ToDecimal256`

2021-03-23 14:33 UTC, pitrou commented on cpp/src/arrow/compute/kernels/scalar_cast_test.cc
> +TEST(Cast, Decimal256ToDecimal) {
`Decimal256ToDecimal128`

2021-03-23 14:33 UTC, pitrou commented on cpp/src/arrow/compute/kernels/scalar_cast_test.cc
> +TEST(Cast, FloatingToDecimal256) {
Don't you want to avoid the code duplication here? This looks like exactly the same test as above.

2021-03-23 14:37 UTC, lidavidm commented
Thanks, looks like I got something backwards…will rework this.

2021-03-24 04:57 UTC, emkornfield commented
@lidavidm is it still worth me taking a look or is the rework going to change things substantially?

2021-03-24 11:42 UTC, lidavidm commented
@emkornfield this should be ready again (was just waiting for CI - looks like MacOS flaked)

2021-03-24 12:04 UTC, pitrou approved these changes
+1, just one comment

2021-03-24 17:40 UTC, closed without merging